/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";

export interface PluginmanagerApiUninstallPluginRequest {
  puginId: string;
}

/**
 * PluginmanagerApi - interface
 *
 * @export
 * @interface PluginmanagerApiInterface
 */
export interface PluginmanagerApiInterface {
  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PluginmanagerApiInterface
   */
  installedPluginsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: string }>>;

  /**
   */
  installedPlugins(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: string }>;

  /**
   *
   * @param {string} puginId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof PluginmanagerApiInterface
   */
  uninstallPluginRaw(
    requestParameters: PluginmanagerApiUninstallPluginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  uninstallPlugin(
    requestParameters: PluginmanagerApiUninstallPluginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;
}

/**
 *
 */
export class PluginmanagerApi
  extends runtime.BaseAPI
  implements PluginmanagerApiInterface
{
  /**
   */
  async installedPluginsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: string }>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/plugins/installed`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async installedPlugins(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: string }> {
    const response = await this.installedPluginsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async uninstallPluginRaw(
    requestParameters: PluginmanagerApiUninstallPluginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["puginId"] == null) {
      throw new runtime.RequiredError(
        "puginId",
        'Required parameter "puginId" was null or undefined when calling uninstallPlugin().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["puginId"] != null) {
      queryParameters["puginId"] = requestParameters["puginId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/plugins/uninstall`,
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async uninstallPlugin(
    requestParameters: PluginmanagerApiUninstallPluginRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.uninstallPluginRaw(requestParameters, initOverrides);
  }
}
