/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ResponseSuccess,
} from '../models/index';
import {
    ResponseSuccessFromJSON,
    ResponseSuccessToJSON,
} from '../models/index';

/**
 * StreamApi - interface
 * 
 * @export
 * @interface StreamApiInterface
 */
export interface StreamApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof StreamApiInterface
     */
    retrieveStreamOpsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSuccess>>;

    /**
     */
    retrieveStreamOps(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSuccess>;

}

/**
 * 
 */
export class StreamApi extends runtime.BaseAPI implements StreamApiInterface {

    /**
     */
    async retrieveStreamOpsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ResponseSuccess>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/rest/v1/stream/put`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSuccessFromJSON(jsonValue));
    }

    /**
     */
    async retrieveStreamOps(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ResponseSuccess> {
        const response = await this.retrieveStreamOpsRaw(initOverrides);
        return await response.value();
    }

}
