/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
    AllBucketStats,
    BucketStatistics,
    BucketUiItem,
    Change,
    ChartData,
    DataResponse,
    Document, MultiValueMapStringString,
    NewBucket,
} from '../models/index';
import {
    AllBucketStatsFromJSON,
    AllBucketStatsToJSON,
    BucketStatisticsFromJSON,
    BucketStatisticsToJSON,
    BucketUiItemFromJSON,
    BucketUiItemToJSON,
    ChangeFromJSON,
    ChangeToJSON,
    ChartDataFromJSON,
    ChartDataToJSON,
    DataResponseFromJSON,
    DataResponseToJSON,
    DocumentFromJSON,
    DocumentToJSON,
    NewBucketFromJSON,
    NewBucketToJSON,
} from '../models/index';

export interface UIApiCreateBucket1Request {
    bucket: NewBucket;
}

export interface UIApiDashboardSearchDocumentsRequest {
    search: string;
}

export interface UIApiFoldersChangedThatDayRequest {
    yyyyMMdd: string;
}

export interface UIApiGetBucketStatsRequest {
    bucket: string;
}

export interface UIApiListBucketsRequest {
    filter?: string;
    favourite?: boolean;
}

export interface UIApiTagFavouriteBucketRequest {
    bucket: string;
    favourite: boolean;
}

export interface UIApiUpdateBucketRequest {
    _formParams: MultiValueMapStringString;
    name: string;
}

/**
 * UIApi - interface
 * 
 * @export
 * @interface UIApiInterface
 */
export interface UIApiInterface {
    /**
     * 
     * @param {NewBucket} bucket 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    createBucket1Raw(requestParameters: UIApiCreateBucket1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>>;

    /**
     */
    createBucket1(requestParameters: UIApiCreateBucket1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    dashboardBucketsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BucketUiItem>>>;

    /**
     */
    dashboardBuckets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BucketUiItem>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    dashboardBucketsChartRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChartData>>;

    /**
     */
    dashboardBucketsChart(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChartData>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    dashboardFavDocumentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Document>>>;

    /**
     */
    dashboardFavDocuments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Document>>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    dashboardRecentDocumentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Document>>>;

    /**
     */
    dashboardRecentDocuments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Document>>;

    /**
     * 
     * @param {string} search 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    dashboardSearchDocumentsRaw(requestParameters: UIApiDashboardSearchDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Document>>>;

    /**
     */
    dashboardSearchDocuments(requestParameters: UIApiDashboardSearchDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Document>>;

    /**
     * 
     * @param {string} yyyyMMdd 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    foldersChangedThatDayRaw(requestParameters: UIApiFoldersChangedThatDayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Change>>>;

    /**
     */
    foldersChangedThatDay(requestParameters: UIApiFoldersChangedThatDayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Change>>;

    /**
     * 
     * @param {string} bucket 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    getBucketStatsRaw(requestParameters: UIApiGetBucketStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BucketStatistics>>;

    /**
     */
    getBucketStats(requestParameters: UIApiGetBucketStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BucketStatistics>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    getSizeOfAllBucketsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllBucketStats>>;

    /**
     */
    getSizeOfAllBuckets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllBucketStats>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    getUserActivityRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: number; }>>;

    /**
     */
    getUserActivity(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: number; }>;

    /**
     * 
     * @param {string} [filter] 
     * @param {boolean} [favourite] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    listBucketsRaw(requestParameters: UIApiListBucketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BucketUiItem>>>;

    /**
     */
    listBuckets(requestParameters: UIApiListBucketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BucketUiItem>>;

    /**
     * 
     * @param {string} bucket 
     * @param {boolean} favourite 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    tagFavouriteBucketRaw(requestParameters: UIApiTagFavouriteBucketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataResponse>>;

    /**
     */
    tagFavouriteBucket(requestParameters: UIApiTagFavouriteBucketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataResponse>;

    /**
     * 
     * @param {MultiValueMapStringString} _formParams 
     * @param {string} name 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof UIApiInterface
     */
    updateBucketRaw(requestParameters: UIApiUpdateBucketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataResponse>>;

    /**
     */
    updateBucket(requestParameters: UIApiUpdateBucketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataResponse>;

}

/**
 * 
 */
export class UIApi extends runtime.BaseAPI implements UIApiInterface {

    /**
     */
    async createBucket1Raw(requestParameters: UIApiCreateBucket1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: string; }>> {
        if (requestParameters['bucket'] == null) {
            throw new runtime.RequiredError(
                'bucket',
                'Required parameter "bucket" was null or undefined when calling createBucket1().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['bucket'] != null) {
            queryParameters['bucket'] = requestParameters['bucket'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/meta/buckets`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async createBucket1(requestParameters: UIApiCreateBucket1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: string; }> {
        const response = await this.createBucket1Raw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async dashboardBucketsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BucketUiItem>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/dashboard/buckets/favourite`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BucketUiItemFromJSON));
    }

    /**
     */
    async dashboardBuckets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BucketUiItem>> {
        const response = await this.dashboardBucketsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async dashboardBucketsChartRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChartData>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/dashboard/buckets/chart`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChartDataFromJSON(jsonValue));
    }

    /**
     */
    async dashboardBucketsChart(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChartData> {
        const response = await this.dashboardBucketsChartRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async dashboardFavDocumentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Document>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/dashboard/documents/favourite`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DocumentFromJSON));
    }

    /**
     */
    async dashboardFavDocuments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Document>> {
        const response = await this.dashboardFavDocumentsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async dashboardRecentDocumentsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Document>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/dashboard/documents/recent`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DocumentFromJSON));
    }

    /**
     */
    async dashboardRecentDocuments(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Document>> {
        const response = await this.dashboardRecentDocumentsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async dashboardSearchDocumentsRaw(requestParameters: UIApiDashboardSearchDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Document>>> {
        if (requestParameters['search'] == null) {
            throw new runtime.RequiredError(
                'search',
                'Required parameter "search" was null or undefined when calling dashboardSearchDocuments().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['search'] != null) {
            queryParameters['search'] = requestParameters['search'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/dashboard/documents/search`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DocumentFromJSON));
    }

    /**
     */
    async dashboardSearchDocuments(requestParameters: UIApiDashboardSearchDocumentsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Document>> {
        const response = await this.dashboardSearchDocumentsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async foldersChangedThatDayRaw(requestParameters: UIApiFoldersChangedThatDayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Change>>> {
        if (requestParameters['yyyyMMdd'] == null) {
            throw new runtime.RequiredError(
                'yyyyMMdd',
                'Required parameter "yyyyMMdd" was null or undefined when calling foldersChangedThatDay().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/dashboard/changes/{yyyyMMdd}`.replace(`{${"yyyyMMdd"}}`, encodeURIComponent(String(requestParameters['yyyyMMdd']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ChangeFromJSON));
    }

    /**
     */
    async foldersChangedThatDay(requestParameters: UIApiFoldersChangedThatDayRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Change>> {
        const response = await this.foldersChangedThatDayRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getBucketStatsRaw(requestParameters: UIApiGetBucketStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BucketStatistics>> {
        if (requestParameters['bucket'] == null) {
            throw new runtime.RequiredError(
                'bucket',
                'Required parameter "bucket" was null or undefined when calling getBucketStats().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['bucket'] != null) {
            queryParameters['bucket'] = requestParameters['bucket'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/meta/bucketstats`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BucketStatisticsFromJSON(jsonValue));
    }

    /**
     */
    async getBucketStats(requestParameters: UIApiGetBucketStatsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BucketStatistics> {
        const response = await this.getBucketStatsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async getSizeOfAllBucketsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AllBucketStats>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/meta/bucketsize`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AllBucketStatsFromJSON(jsonValue));
    }

    /**
     */
    async getSizeOfAllBuckets(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AllBucketStats> {
        const response = await this.getSizeOfAllBucketsRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getUserActivityRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<{ [key: string]: number; }>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/dashboard/user/activity`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async getUserActivity(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<{ [key: string]: number; }> {
        const response = await this.getUserActivityRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async listBucketsRaw(requestParameters: UIApiListBucketsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<BucketUiItem>>> {
        const queryParameters: any = {};

        if (requestParameters['filter'] != null) {
            queryParameters['filter'] = requestParameters['filter'];
        }

        if (requestParameters['favourite'] != null) {
            queryParameters['favourite'] = requestParameters['favourite'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/meta/bucketlist`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(BucketUiItemFromJSON));
    }

    /**
     */
    async listBuckets(requestParameters: UIApiListBucketsRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<BucketUiItem>> {
        const response = await this.listBucketsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async tagFavouriteBucketRaw(requestParameters: UIApiTagFavouriteBucketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataResponse>> {
        if (requestParameters['bucket'] == null) {
            throw new runtime.RequiredError(
                'bucket',
                'Required parameter "bucket" was null or undefined when calling tagFavouriteBucket().'
            );
        }

        if (requestParameters['favourite'] == null) {
            throw new runtime.RequiredError(
                'favourite',
                'Required parameter "favourite" was null or undefined when calling tagFavouriteBucket().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['bucket'] != null) {
            queryParameters['bucket'] = requestParameters['bucket'];
        }

        if (requestParameters['favourite'] != null) {
            queryParameters['favourite'] = requestParameters['favourite'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/meta/buckets/favourite`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataResponseFromJSON(jsonValue));
    }

    /**
     */
    async tagFavouriteBucket(requestParameters: UIApiTagFavouriteBucketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataResponse> {
        const response = await this.tagFavouriteBucketRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async updateBucketRaw(requestParameters: UIApiUpdateBucketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataResponse>> {
        if (requestParameters['_formParams'] == null) {
            throw new runtime.RequiredError(
                '_formParams',
                'Required parameter "_formParams" was null or undefined when calling updateBucket().'
            );
        }

        if (requestParameters['name'] == null) {
            throw new runtime.RequiredError(
                'name',
                'Required parameter "name" was null or undefined when calling updateBucket().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['_formParams'] != null) {
            queryParameters['formParams'] = requestParameters['_formParams'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && (this.configuration.username !== undefined || this.configuration.password !== undefined)) {
            headerParameters["Authorization"] = "Basic " + btoa(this.configuration.username + ":" + this.configuration.password);
        }
        const response = await this.request({
            path: `/api/ui/v1/meta/buckets/{name}`.replace(`{${"name"}}`, encodeURIComponent(String(requestParameters['name']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataResponseFromJSON(jsonValue));
    }

    /**
     */
    async updateBucket(requestParameters: UIApiUpdateBucketRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataResponse> {
        const response = await this.updateBucketRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
