/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from "../runtime";
import type {
  CredentialsWrapper,
  LadonPermission,
  Permission,
  RoleEntry,
  RoleWrapper,
  UserDataWrapper,
  UserEntry,
  UserLogins,
  UserWrapper,
} from "../models/index";
import {
  CredentialsWrapperFromJSON,
  CredentialsWrapperToJSON,
  LadonPermissionFromJSON,
  LadonPermissionToJSON,
  PermissionFromJSON,
  PermissionToJSON,
  RoleEntryFromJSON,
  RoleEntryToJSON,
  RoleWrapperFromJSON,
  RoleWrapperToJSON,
  UserDataWrapperFromJSON,
  UserDataWrapperToJSON,
  UserEntryFromJSON,
  UserEntryToJSON,
  UserLoginsFromJSON,
  UserLoginsToJSON,
  UserWrapperFromJSON,
  UserWrapperToJSON,
} from "../models/index";

export interface UsermanagerApiAddAvatarRequest {
  userId: string;
  uploadFullpath: string;
  upload: Blob;
}

export interface UsermanagerApiAddPermissionForRoleRequest {
  roleId: string;
  permissionId: string;
}

export interface UsermanagerApiAddPermissionForUserRequest {
  userId: string;
  permissionId: string;
}

export interface UsermanagerApiAddRoleForUserRequest {
  userId: string;
  roleId: string;
}

export interface UsermanagerApiAddUserRequest {
  userWrapper: UserWrapper;
}

export interface UsermanagerApiCreatePermissionsRequest {
  ladonPermission: LadonPermission;
}

export interface UsermanagerApiCreateRoleRequest {
  roleWrapper: RoleWrapper;
}

export interface UsermanagerApiDeleteRoleRequest {
  roleId: string;
}

export interface UsermanagerApiDeleteRoleForUserRequest {
  userId: string;
  roleId: string;
}

export interface UsermanagerApiDeleteUserRequest {
  userId: string;
}

export interface UsermanagerApiGetLoginLogsRequest {
  userId: string;
}

export interface UsermanagerApiGetPermissionsForRoleRequest {
  roleId: string;
}

export interface UsermanagerApiGetPermissionsForUserRequest {
  userId: string;
}

export interface UsermanagerApiGetRoleForUserRequest {
  userId: string;
}

export interface UsermanagerApiGetUserDataRequest {
  userId: string;
}

export interface UsermanagerApiGetUsersForRoleRequest {
  roleId: string;
}

export interface UsermanagerApiRemovePermissionRequest {
  permissionId: string;
}

export interface UsermanagerApiRemovePermissionFromRoleRequest {
  roleId: string;
  permissionId: string;
}

export interface UsermanagerApiRemovePermissionFromUserRequest {
  userId: string;
  permissionId: string;
}

export interface UsermanagerApiSetCredentialsRequest {
  userId: string;
  body: string;
}

export interface UsermanagerApiUpdateCredentialsRequest {
  userId: string;
  credentialsWrapper: CredentialsWrapper;
}

export interface UsermanagerApiUpdateUserRequest {
  userId: string;
  userDataWrapper: UserDataWrapper;
}

/**
 * UsermanagerApi - interface
 *
 * @export
 * @interface UsermanagerApiInterface
 */
export interface UsermanagerApiInterface {
  /**
   *
   * @param {string} userId
   * @param {string} uploadFullpath
   * @param {Blob} upload
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  addAvatarRaw(
    requestParameters: UsermanagerApiAddAvatarRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  addAvatar(
    requestParameters: UsermanagerApiAddAvatarRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} roleId
   * @param {string} permissionId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  addPermissionForRoleRaw(
    requestParameters: UsermanagerApiAddPermissionForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  addPermissionForRole(
    requestParameters: UsermanagerApiAddPermissionForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} userId
   * @param {string} permissionId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  addPermissionForUserRaw(
    requestParameters: UsermanagerApiAddPermissionForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  addPermissionForUser(
    requestParameters: UsermanagerApiAddPermissionForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} userId
   * @param {string} roleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  addRoleForUserRaw(
    requestParameters: UsermanagerApiAddRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  addRoleForUser(
    requestParameters: UsermanagerApiAddRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {UserWrapper} userWrapper
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  addUserRaw(
    requestParameters: UsermanagerApiAddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: string }>>;

  /**
   */
  addUser(
    requestParameters: UsermanagerApiAddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: string }>;

  /**
   *
   * @param {LadonPermission} ladonPermission
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  createPermissionsRaw(
    requestParameters: UsermanagerApiCreatePermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>>;

  /**
   */
  createPermissions(
    requestParameters: UsermanagerApiCreatePermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object>;

  /**
   *
   * @param {RoleWrapper} roleWrapper
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  createRoleRaw(
    requestParameters: UsermanagerApiCreateRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  createRole(
    requestParameters: UsermanagerApiCreateRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} roleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  deleteRoleRaw(
    requestParameters: UsermanagerApiDeleteRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  deleteRole(
    requestParameters: UsermanagerApiDeleteRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} userId
   * @param {string} roleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  deleteRoleForUserRaw(
    requestParameters: UsermanagerApiDeleteRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  deleteRoleForUser(
    requestParameters: UsermanagerApiDeleteRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  deleteUserRaw(
    requestParameters: UsermanagerApiDeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  deleteUser(
    requestParameters: UsermanagerApiDeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getAllPermissionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>>;

  /**
   */
  getAllPermissions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Permission>>;

  /**
   *
   * @param {string} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getLoginLogsRaw(
    requestParameters: UsermanagerApiGetLoginLogsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<UserLogins>>>;

  /**
   */
  getLoginLogs(
    requestParameters: UsermanagerApiGetLoginLogsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<UserLogins>>;

  /**
   *
   * @param {string} roleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getPermissionsForRoleRaw(
    requestParameters: UsermanagerApiGetPermissionsForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>>;

  /**
   */
  getPermissionsForRole(
    requestParameters: UsermanagerApiGetPermissionsForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Permission>>;

  /**
   *
   * @param {string} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getPermissionsForUserRaw(
    requestParameters: UsermanagerApiGetPermissionsForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>>;

  /**
   */
  getPermissionsForUser(
    requestParameters: UsermanagerApiGetPermissionsForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Permission>>;

  /**
   *
   * @param {string} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getRoleForUserRaw(
    requestParameters: UsermanagerApiGetRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>>;

  /**
   */
  getRoleForUser(
    requestParameters: UsermanagerApiGetRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getRolesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RoleEntry>>>;

  /**
   */
  getRoles(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RoleEntry>>;

  /**
   *
   * @param {string} userId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getUserDataRaw(
    requestParameters: UsermanagerApiGetUserDataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UserDataWrapper>>;

  /**
   */
  getUserData(
    requestParameters: UsermanagerApiGetUserDataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UserDataWrapper>;

  /**
   *
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getUsersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<UserEntry>>>;

  /**
   */
  getUsers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<UserEntry>>;

  /**
   *
   * @param {string} roleId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  getUsersForRoleRaw(
    requestParameters: UsermanagerApiGetUsersForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>>;

  /**
   */
  getUsersForRole(
    requestParameters: UsermanagerApiGetUsersForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>>;

  /**
   *
   * @param {string} permissionId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  removePermissionRaw(
    requestParameters: UsermanagerApiRemovePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>>;

  /**
   */
  removePermission(
    requestParameters: UsermanagerApiRemovePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object>;

  /**
   *
   * @param {string} roleId
   * @param {string} permissionId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  removePermissionFromRoleRaw(
    requestParameters: UsermanagerApiRemovePermissionFromRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  removePermissionFromRole(
    requestParameters: UsermanagerApiRemovePermissionFromRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} userId
   * @param {string} permissionId
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  removePermissionFromUserRaw(
    requestParameters: UsermanagerApiRemovePermissionFromUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  removePermissionFromUser(
    requestParameters: UsermanagerApiRemovePermissionFromUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} userId
   * @param {string} body
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  setCredentialsRaw(
    requestParameters: UsermanagerApiSetCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  setCredentials(
    requestParameters: UsermanagerApiSetCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} userId
   * @param {CredentialsWrapper} credentialsWrapper
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  updateCredentialsRaw(
    requestParameters: UsermanagerApiUpdateCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  updateCredentials(
    requestParameters: UsermanagerApiUpdateCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;

  /**
   *
   * @param {string} userId
   * @param {UserDataWrapper} userDataWrapper
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof UsermanagerApiInterface
   */
  updateUserRaw(
    requestParameters: UsermanagerApiUpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>>;

  /**
   */
  updateUser(
    requestParameters: UsermanagerApiUpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void>;
}

/**
 *
 */
export class UsermanagerApi
  extends runtime.BaseAPI
  implements UsermanagerApiInterface
{
  /**
   */
  async addAvatarRaw(
    requestParameters: UsermanagerApiAddAvatarRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling addAvatar().',
      );
    }

    if (requestParameters["uploadFullpath"] == null) {
      throw new runtime.RequiredError(
        "uploadFullpath",
        'Required parameter "uploadFullpath" was null or undefined when calling addAvatar().',
      );
    }

    if (requestParameters["upload"] == null) {
      throw new runtime.RequiredError(
        "upload",
        'Required parameter "upload" was null or undefined when calling addAvatar().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["uploadFullpath"] != null) {
      queryParameters["upload_fullpath"] = requestParameters["uploadFullpath"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const consumes: runtime.Consume[] = [
      { contentType: "multipart/form-data" },
    ];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters["upload"] != null) {
      formParams.append("upload", requestParameters["upload"] as any);
    }

    const response = await this.request(
      {
        path: `/api/usermanager/users/{userId}/avatar`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addAvatar(
    requestParameters: UsermanagerApiAddAvatarRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addAvatarRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addPermissionForRoleRaw(
    requestParameters: UsermanagerApiAddPermissionForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["roleId"] == null) {
      throw new runtime.RequiredError(
        "roleId",
        'Required parameter "roleId" was null or undefined when calling addPermissionForRole().',
      );
    }

    if (requestParameters["permissionId"] == null) {
      throw new runtime.RequiredError(
        "permissionId",
        'Required parameter "permissionId" was null or undefined when calling addPermissionForRole().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["permissionId"] != null) {
      queryParameters["permissionId"] = requestParameters["permissionId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/role/{roleId}`.replace(
          `{${"roleId"}}`,
          encodeURIComponent(String(requestParameters["roleId"])),
        ),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addPermissionForRole(
    requestParameters: UsermanagerApiAddPermissionForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addPermissionForRoleRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addPermissionForUserRaw(
    requestParameters: UsermanagerApiAddPermissionForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling addPermissionForUser().',
      );
    }

    if (requestParameters["permissionId"] == null) {
      throw new runtime.RequiredError(
        "permissionId",
        'Required parameter "permissionId" was null or undefined when calling addPermissionForUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["permissionId"] != null) {
      queryParameters["permissionId"] = requestParameters["permissionId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/user/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addPermissionForUser(
    requestParameters: UsermanagerApiAddPermissionForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addPermissionForUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addRoleForUserRaw(
    requestParameters: UsermanagerApiAddRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling addRoleForUser().',
      );
    }

    if (requestParameters["roleId"] == null) {
      throw new runtime.RequiredError(
        "roleId",
        'Required parameter "roleId" was null or undefined when calling addRoleForUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["roleId"] != null) {
      queryParameters["roleId"] = requestParameters["roleId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles/user/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addRoleForUser(
    requestParameters: UsermanagerApiAddRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addRoleForUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addUserRaw(
    requestParameters: UsermanagerApiAddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: string }>> {
    if (requestParameters["userWrapper"] == null) {
      throw new runtime.RequiredError(
        "userWrapper",
        'Required parameter "userWrapper" was null or undefined when calling addUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/usermanager/users`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: UserWrapperToJSON(requestParameters["userWrapper"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async addUser(
    requestParameters: UsermanagerApiAddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: string }> {
    const response = await this.addUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async createPermissionsRaw(
    requestParameters: UsermanagerApiCreatePermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters["ladonPermission"] == null) {
      throw new runtime.RequiredError(
        "ladonPermission",
        'Required parameter "ladonPermission" was null or undefined when calling createPermissions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/usermanager/permissions`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: LadonPermissionToJSON(requestParameters["ladonPermission"]),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async createPermissions(
    requestParameters: UsermanagerApiCreatePermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.createPermissionsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async createRoleRaw(
    requestParameters: UsermanagerApiCreateRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["roleWrapper"] == null) {
      throw new runtime.RequiredError(
        "roleWrapper",
        'Required parameter "roleWrapper" was null or undefined when calling createRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/usermanager/roles`,
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: RoleWrapperToJSON(requestParameters["roleWrapper"]),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async createRole(
    requestParameters: UsermanagerApiCreateRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.createRoleRaw(requestParameters, initOverrides);
  }

  /**
   */
  async deleteRoleRaw(
    requestParameters: UsermanagerApiDeleteRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["roleId"] == null) {
      throw new runtime.RequiredError(
        "roleId",
        'Required parameter "roleId" was null or undefined when calling deleteRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles/{roleId}`.replace(
          `{${"roleId"}}`,
          encodeURIComponent(String(requestParameters["roleId"])),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteRole(
    requestParameters: UsermanagerApiDeleteRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteRoleRaw(requestParameters, initOverrides);
  }

  /**
   */
  async deleteRoleForUserRaw(
    requestParameters: UsermanagerApiDeleteRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling deleteRoleForUser().',
      );
    }

    if (requestParameters["roleId"] == null) {
      throw new runtime.RequiredError(
        "roleId",
        'Required parameter "roleId" was null or undefined when calling deleteRoleForUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["roleId"] != null) {
      queryParameters["roleId"] = requestParameters["roleId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles/user/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteRoleForUser(
    requestParameters: UsermanagerApiDeleteRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteRoleForUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async deleteUserRaw(
    requestParameters: UsermanagerApiDeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling deleteUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/users/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteUser(
    requestParameters: UsermanagerApiDeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async getAllPermissionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PermissionFromJSON),
    );
  }

  /**
   */
  async getAllPermissions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Permission>> {
    const response = await this.getAllPermissionsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getLoginLogsRaw(
    requestParameters: UsermanagerApiGetLoginLogsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<UserLogins>>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling getLoginLogs().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/logs/login/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(UserLoginsFromJSON),
    );
  }

  /**
   */
  async getLoginLogs(
    requestParameters: UsermanagerApiGetLoginLogsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<UserLogins>> {
    const response = await this.getLoginLogsRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getPermissionsForRoleRaw(
    requestParameters: UsermanagerApiGetPermissionsForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>> {
    if (requestParameters["roleId"] == null) {
      throw new runtime.RequiredError(
        "roleId",
        'Required parameter "roleId" was null or undefined when calling getPermissionsForRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/role/{roleId}`.replace(
          `{${"roleId"}}`,
          encodeURIComponent(String(requestParameters["roleId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PermissionFromJSON),
    );
  }

  /**
   */
  async getPermissionsForRole(
    requestParameters: UsermanagerApiGetPermissionsForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Permission>> {
    const response = await this.getPermissionsForRoleRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getPermissionsForUserRaw(
    requestParameters: UsermanagerApiGetPermissionsForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling getPermissionsForUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/user/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(PermissionFromJSON),
    );
  }

  /**
   */
  async getPermissionsForUser(
    requestParameters: UsermanagerApiGetPermissionsForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Permission>> {
    const response = await this.getPermissionsForUserRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getRoleForUserRaw(
    requestParameters: UsermanagerApiGetRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling getRoleForUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles/user/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async getRoleForUser(
    requestParameters: UsermanagerApiGetRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.getRoleForUserRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getRolesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RoleEntry>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(RoleEntryFromJSON),
    );
  }

  /**
   */
  async getRoles(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<RoleEntry>> {
    const response = await this.getRolesRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getUserDataRaw(
    requestParameters: UsermanagerApiGetUserDataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UserDataWrapper>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling getUserData().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/users/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      UserDataWrapperFromJSON(jsonValue),
    );
  }

  /**
   */
  async getUserData(
    requestParameters: UsermanagerApiGetUserDataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UserDataWrapper> {
    const response = await this.getUserDataRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async getUsersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<UserEntry>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/users`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(UserEntryFromJSON),
    );
  }

  /**
   */
  async getUsers(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<UserEntry>> {
    const response = await this.getUsersRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getUsersForRoleRaw(
    requestParameters: UsermanagerApiGetUsersForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters["roleId"] == null) {
      throw new runtime.RequiredError(
        "roleId",
        'Required parameter "roleId" was null or undefined when calling getUsersForRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/users/role/{roleId}`.replace(
          `{${"roleId"}}`,
          encodeURIComponent(String(requestParameters["roleId"])),
        ),
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async getUsersForRole(
    requestParameters: UsermanagerApiGetUsersForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.getUsersForRoleRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async removePermissionRaw(
    requestParameters: UsermanagerApiRemovePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters["permissionId"] == null) {
      throw new runtime.RequiredError(
        "permissionId",
        'Required parameter "permissionId" was null or undefined when calling removePermission().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/{permissionId}`.replace(
          `{${"permissionId"}}`,
          encodeURIComponent(String(requestParameters["permissionId"])),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async removePermission(
    requestParameters: UsermanagerApiRemovePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.removePermissionRaw(
      requestParameters,
      initOverrides,
    );
    return await response.value();
  }

  /**
   */
  async removePermissionFromRoleRaw(
    requestParameters: UsermanagerApiRemovePermissionFromRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["roleId"] == null) {
      throw new runtime.RequiredError(
        "roleId",
        'Required parameter "roleId" was null or undefined when calling removePermissionFromRole().',
      );
    }

    if (requestParameters["permissionId"] == null) {
      throw new runtime.RequiredError(
        "permissionId",
        'Required parameter "permissionId" was null or undefined when calling removePermissionFromRole().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["permissionId"] != null) {
      queryParameters["permissionId"] = requestParameters["permissionId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/role/{roleId}`.replace(
          `{${"roleId"}}`,
          encodeURIComponent(String(requestParameters["roleId"])),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async removePermissionFromRole(
    requestParameters: UsermanagerApiRemovePermissionFromRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removePermissionFromRoleRaw(requestParameters, initOverrides);
  }

  /**
   */
  async removePermissionFromUserRaw(
    requestParameters: UsermanagerApiRemovePermissionFromUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling removePermissionFromUser().',
      );
    }

    if (requestParameters["permissionId"] == null) {
      throw new runtime.RequiredError(
        "permissionId",
        'Required parameter "permissionId" was null or undefined when calling removePermissionFromUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters["permissionId"] != null) {
      queryParameters["permissionId"] = requestParameters["permissionId"];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/user/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "DELETE",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async removePermissionFromUser(
    requestParameters: UsermanagerApiRemovePermissionFromUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removePermissionFromUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async setCredentialsRaw(
    requestParameters: UsermanagerApiSetCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling setCredentials().',
      );
    }

    if (requestParameters["body"] == null) {
      throw new runtime.RequiredError(
        "body",
        'Required parameter "body" was null or undefined when calling setCredentials().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/usermanager/user/{userId}/credentials`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "POST",
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters["body"] as any,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async setCredentials(
    requestParameters: UsermanagerApiSetCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.setCredentialsRaw(requestParameters, initOverrides);
  }

  /**
   */
  async updateCredentialsRaw(
    requestParameters: UsermanagerApiUpdateCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling updateCredentials().',
      );
    }

    if (requestParameters["credentialsWrapper"] == null) {
      throw new runtime.RequiredError(
        "credentialsWrapper",
        'Required parameter "credentialsWrapper" was null or undefined when calling updateCredentials().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/usermanager/user/{userId}/credentials`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: CredentialsWrapperToJSON(requestParameters["credentialsWrapper"]),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async updateCredentials(
    requestParameters: UsermanagerApiUpdateCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.updateCredentialsRaw(requestParameters, initOverrides);
  }

  /**
   */
  async updateUserRaw(
    requestParameters: UsermanagerApiUpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters["userId"] == null) {
      throw new runtime.RequiredError(
        "userId",
        'Required parameter "userId" was null or undefined when calling updateUser().',
      );
    }

    if (requestParameters["userDataWrapper"] == null) {
      throw new runtime.RequiredError(
        "userDataWrapper",
        'Required parameter "userDataWrapper" was null or undefined when calling updateUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    const response = await this.request(
      {
        path: `/api/usermanager/users/{userId}`.replace(
          `{${"userId"}}`,
          encodeURIComponent(String(requestParameters["userId"])),
        ),
        method: "PUT",
        headers: headerParameters,
        query: queryParameters,
        body: UserDataWrapperToJSON(requestParameters["userDataWrapper"]),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async updateUser(
    requestParameters: UsermanagerApiUpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.updateUserRaw(requestParameters, initOverrides);
  }
}
