/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BucketAction
 */
export interface BucketAction {
    /**
     * 
     * @type {string}
     * @memberof BucketAction
     */
    i18nName?: string;
    /**
     * 
     * @type {string}
     * @memberof BucketAction
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof BucketAction
     */
    actionId?: string;
    /**
     * 
     * @type {string}
     * @memberof BucketAction
     */
    icon?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof BucketAction
     */
    selection?: Array<string>;
}

/**
 * Check if a given object implements the BucketAction interface.
 */
export function instanceOfBucketAction(value: object): value is BucketAction {
    return true;
}

export function BucketActionFromJSON(json: any): BucketAction {
    return BucketActionFromJSONTyped(json, false);
}

export function BucketActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketAction {
    if (json == null) {
        return json;
    }
    return {
        
        'i18nName': json['i18nName'] == null ? undefined : json['i18nName'],
        'label': json['label'] == null ? undefined : json['label'],
        'actionId': json['actionId'] == null ? undefined : json['actionId'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'selection': json['selection'] == null ? undefined : json['selection'],
    };
}

export function BucketActionToJSON(value?: BucketAction | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'i18nName': value['i18nName'],
        'label': value['label'],
        'actionId': value['actionId'],
        'icon': value['icon'],
        'selection': value['selection'],
    };
}

