/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConverterParameter
 */
export interface ConverterParameter {
    /**
     * 
     * @type {string}
     * @memberof ConverterParameter
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ConverterParameter
     */
    description: string;
    /**
     * 
     * @type {boolean}
     * @memberof ConverterParameter
     */
    optional: boolean;
}

/**
 * Check if a given object implements the ConverterParameter interface.
 */
export function instanceOfConverterParameter(value: object): value is ConverterParameter {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('optional' in value) || value['optional'] === undefined) return false;
    return true;
}

export function ConverterParameterFromJSON(json: any): ConverterParameter {
    return ConverterParameterFromJSONTyped(json, false);
}

export function ConverterParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConverterParameter {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
        'optional': json['optional'],
    };
}

export function ConverterParameterToJSON(value?: ConverterParameter | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'description': value['description'],
        'optional': value['optional'],
    };
}

