/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DocumentMetadata } from './DocumentMetadata';
import { DocumentMetadataFromJSON, DocumentMetadataFromJSONTyped, DocumentMetadataToJSON } from './DocumentMetadata';

/**
 *
 * @export
 * @interface Document
 */
export interface Document {
  /**
   *
   * @type {string}
   * @memberof Document
   */
  contentType?: string;
  /**
   *
   * @type {string}
   * @memberof Document
   */
  created?: string;
  /**
   *
   * @type {string}
   * @memberof Document
   */
  lastModified?: string;
  /**
   *
   * @type {string}
   * @memberof Document
   */
  bucket?: string;
  /**
   *
   * @type {string}
   * @memberof Document
   */
  key?: string;
  /**
   *
   * @type {string}
   * @memberof Document
   */
  path?: string;
  /**
   *
   * @type {string}
   * @memberof Document
   */
  etag?: string;
  /**
   *
   * @type {DocumentMetadata}
   * @memberof Document
   */
  metadata?: DocumentMetadata;
  /**
   *
   * @type {string}
   * @memberof Document
   */
  owner?: string;
  /**
   *
   * @type {number}
   * @memberof Document
   */
  size?: number;
  /**
   *
   * @type {string}
   * @memberof Document
   */
  version?: string;
  /**
   *
   * @type {boolean}
   * @memberof Document
   */
  isFolder?: boolean;
}

/**
 * Check if a given object implements the Document interface.
 */
export function instanceOfDocument(value: object): value is Document {
  return true;
}

export function DocumentFromJSON(json: any): Document {
  return DocumentFromJSONTyped(json, false);
}

export function DocumentFromJSONTyped(json: any, ignoreDiscriminator: boolean): Document {
  if (json == null) {
    return json;
  }
  return {
    contentType: json['content-type'] == null ? undefined : json['content-type'],
    created: json['created'] == null ? undefined : json['created'],
    lastModified: json['last-modified'] == null ? undefined : json['last-modified'],
    bucket: json['bucket'] == null ? undefined : json['bucket'],
    key: json['key'] == null ? undefined : json['key'],
    path: json['path'] == null ? undefined : json['path'],
    etag: json['etag'] == null ? undefined : json['etag'],
    metadata: json['metadata'] == null ? undefined : DocumentMetadataFromJSON(json['metadata']),
    owner: json['owner'] == null ? undefined : json['owner'],
    size: json['size'] == null ? undefined : json['size'],
    version: json['version'] == null ? undefined : json['version'],
    isFolder: json['isFolder'] == null ? undefined : json['isFolder'],
  };
}

export function DocumentToJSON(value?: Document | null): any {
  if (value == null) {
    return value;
  }
  return {
    'content-type': value['contentType'],
    created: value['created'],
    'last-modified': value['lastModified'],
    bucket: value['bucket'],
    key: value['key'],
    path: value['path'],
    etag: value['etag'],
    metadata: DocumentMetadataToJSON(value['metadata']),
    owner: value['owner'],
    size: value['size'],
    version: value['version'],
    isFolder: value['isFolder'],
  };
}
