/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 *
 * @export
 * @interface DocumentMetadata
 */
export interface DocumentMetadata {
  [key: string]: string | any;
  /**
   *
   * @type {boolean}
   * @memberof DocumentMetadata
   */
  empty?: boolean;
}

/**
 * Check if a given object implements the DocumentMetadata interface.
 */
export function instanceOfDocumentMetadata(value: object): value is DocumentMetadata {
  return true;
}

export function DocumentMetadataFromJSON(json: any): DocumentMetadata {
  return DocumentMetadataFromJSONTyped(json, false);
}

export function DocumentMetadataFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentMetadata {
  if (json == null) {
    return json;
  }
  return {
    ...json,
    empty: json['empty'] == null ? undefined : json['empty'],
  };
}

export function DocumentMetadataToJSON(value?: DocumentMetadata | null): any {
  if (value == null) {
    return value;
  }
  return {
    ...value,
    empty: value['empty'],
  };
}
