/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional } from "@angular/core";
import {
	HttpClient,
	HttpHeaders,
	HttpParams,
	HttpResponse,
	HttpEvent,
	HttpParameterCodec,
	HttpContext,
} from "@angular/common/http";
import { CustomHttpParameterCodec } from "../encoder";
import { Observable } from "rxjs";

// @ts-ignore
import { Bucket } from "../model/bucket";
// @ts-ignore
import { BucketAction } from "../model/bucketAction";
// @ts-ignore
import { CreateBucketRequest } from "../model/createBucketRequest";
// @ts-ignore
import { ResponseSuccess } from "../model/responseSuccess";

// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS } from "../variables";
import { Configuration } from "../configuration";

@Injectable({
	providedIn: "root",
})
export class BucketsService {
	protected basePath = "/admin";
	public defaultHeaders = new HttpHeaders();
	public configuration = new Configuration();
	public encoder: HttpParameterCodec;

	constructor(
		protected httpClient: HttpClient,
		@Optional() @Inject(BASE_PATH) basePath: string | string[],
		@Optional() configuration: Configuration
	) {
		if (configuration) {
			this.configuration = configuration;
		}
		if (typeof this.configuration.basePath !== "string") {
			const firstBasePath = Array.isArray(basePath) ? basePath[0] : undefined;
			if (firstBasePath != undefined) {
				basePath = firstBasePath;
			}

			if (typeof basePath !== "string") {
				basePath = this.basePath;
			}
			this.configuration.basePath = basePath;
		}
		this.encoder = this.configuration.encoder || new CustomHttpParameterCodec();
	}

	// @ts-ignore
	private addToHttpParams(httpParams: HttpParams, value: any, key?: string): HttpParams {
		if (typeof value === "object" && value instanceof Date === false) {
			httpParams = this.addToHttpParamsRecursive(httpParams, value);
		} else {
			httpParams = this.addToHttpParamsRecursive(httpParams, value, key);
		}
		return httpParams;
	}

	private addToHttpParamsRecursive(httpParams: HttpParams, value?: any, key?: string): HttpParams {
		if (value == null) {
			return httpParams;
		}

		if (typeof value === "object") {
			if (Array.isArray(value)) {
				(value as any[]).forEach((elem) => (httpParams = this.addToHttpParamsRecursive(httpParams, elem, key)));
			} else if (value instanceof Date) {
				if (key != null) {
					httpParams = httpParams.append(key, (value as Date).toISOString().substring(0, 10));
				} else {
					throw Error("key may not be null if value is Date");
				}
			} else {
				Object.keys(value).forEach(
					(k) => (httpParams = this.addToHttpParamsRecursive(httpParams, value[k], key != null ? `${key}.${k}` : k))
				);
			}
		} else if (key != null) {
			httpParams = httpParams.append(key, value);
		} else {
			throw Error("key may not be null if value is not object or array");
		}
		return httpParams;
	}

	/**
	 * @param bucket
	 * @param bucketAction
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 */
	public applyBucketAction(
		bucket: string,
		bucketAction: BucketAction,
		observe?: "body",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<ResponseSuccess>;
	public applyBucketAction(
		bucket: string,
		bucketAction: BucketAction,
		observe?: "response",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpResponse<ResponseSuccess>>;
	public applyBucketAction(
		bucket: string,
		bucketAction: BucketAction,
		observe?: "events",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpEvent<ResponseSuccess>>;
	public applyBucketAction(
		bucket: string,
		bucketAction: BucketAction,
		observe: any = "body",
		reportProgress: boolean = false,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<any> {
		if (bucket === null || bucket === undefined) {
			throw new Error("Required parameter bucket was null or undefined when calling applyBucketAction.");
		}
		if (bucketAction === null || bucketAction === undefined) {
			throw new Error("Required parameter bucketAction was null or undefined when calling applyBucketAction.");
		}

		let localVarHeaders = this.defaultHeaders;

		let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
		if (localVarHttpHeaderAcceptSelected === undefined) {
			// to determine the Accept header
			const httpHeaderAccepts: string[] = ["application/json"];
			localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
		}
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set("Accept", localVarHttpHeaderAcceptSelected);
		}

		let localVarHttpContext: HttpContext | undefined = options && options.context;
		if (localVarHttpContext === undefined) {
			localVarHttpContext = new HttpContext();
		}

		let localVarTransferCache: boolean | undefined = options && options.transferCache;
		if (localVarTransferCache === undefined) {
			localVarTransferCache = true;
		}

		// to determine the Content-Type header
		const consumes: string[] = ["application/json"];
		const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
		if (httpContentTypeSelected !== undefined) {
			localVarHeaders = localVarHeaders.set("Content-Type", httpContentTypeSelected);
		}

		let responseType_: "text" | "json" | "blob" = "json";
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith("text")) {
				responseType_ = "text";
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = "json";
			} else {
				responseType_ = "blob";
			}
		}

		let localVarPath = `/api/rest/v1/actions/bucket/${this.configuration.encodeParam({
			name: "bucket",
			value: bucket,
			in: "path",
			style: "simple",
			explode: false,
			dataType: "string",
			dataFormat: undefined,
		})}`;
		return this.httpClient.request<ResponseSuccess>("put", `${this.configuration.basePath}${localVarPath}`, {
			context: localVarHttpContext,
			body: bucketAction,
			responseType: <any>responseType_,
			withCredentials: this.configuration.withCredentials,
			headers: localVarHeaders,
			observe: observe,
			transferCache: localVarTransferCache,
			reportProgress: reportProgress,
		});
	}

	/**
	 * @param createBucketRequest
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 */
	public createBucket(
		createBucketRequest: CreateBucketRequest,
		observe?: "body",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<Bucket>;
	public createBucket(
		createBucketRequest: CreateBucketRequest,
		observe?: "response",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpResponse<Bucket>>;
	public createBucket(
		createBucketRequest: CreateBucketRequest,
		observe?: "events",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpEvent<Bucket>>;
	public createBucket(
		createBucketRequest: CreateBucketRequest,
		observe: any = "body",
		reportProgress: boolean = false,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<any> {
		if (createBucketRequest === null || createBucketRequest === undefined) {
			throw new Error("Required parameter createBucketRequest was null or undefined when calling createBucket.");
		}

		let localVarHeaders = this.defaultHeaders;

		let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
		if (localVarHttpHeaderAcceptSelected === undefined) {
			// to determine the Accept header
			const httpHeaderAccepts: string[] = ["application/json"];
			localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
		}
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set("Accept", localVarHttpHeaderAcceptSelected);
		}

		let localVarHttpContext: HttpContext | undefined = options && options.context;
		if (localVarHttpContext === undefined) {
			localVarHttpContext = new HttpContext();
		}

		let localVarTransferCache: boolean | undefined = options && options.transferCache;
		if (localVarTransferCache === undefined) {
			localVarTransferCache = true;
		}

		// to determine the Content-Type header
		const consumes: string[] = ["application/json"];
		const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
		if (httpContentTypeSelected !== undefined) {
			localVarHeaders = localVarHeaders.set("Content-Type", httpContentTypeSelected);
		}

		let responseType_: "text" | "json" | "blob" = "json";
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith("text")) {
				responseType_ = "text";
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = "json";
			} else {
				responseType_ = "blob";
			}
		}

		let localVarPath = `/api/rest/v1/meta/buckets`;
		return this.httpClient.request<Bucket>("put", `${this.configuration.basePath}${localVarPath}`, {
			context: localVarHttpContext,
			body: createBucketRequest,
			responseType: <any>responseType_,
			withCredentials: this.configuration.withCredentials,
			headers: localVarHeaders,
			observe: observe,
			transferCache: localVarTransferCache,
			reportProgress: reportProgress,
		});
	}

	/**
	 * @param bucket
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 */
	public deleteBucket(
		bucket: string,
		observe?: "body",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<ResponseSuccess>;
	public deleteBucket(
		bucket: string,
		observe?: "response",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpResponse<ResponseSuccess>>;
	public deleteBucket(
		bucket: string,
		observe?: "events",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpEvent<ResponseSuccess>>;
	public deleteBucket(
		bucket: string,
		observe: any = "body",
		reportProgress: boolean = false,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<any> {
		if (bucket === null || bucket === undefined) {
			throw new Error("Required parameter bucket was null or undefined when calling deleteBucket.");
		}

		let localVarHeaders = this.defaultHeaders;

		let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
		if (localVarHttpHeaderAcceptSelected === undefined) {
			// to determine the Accept header
			const httpHeaderAccepts: string[] = ["application/json"];
			localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
		}
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set("Accept", localVarHttpHeaderAcceptSelected);
		}

		let localVarHttpContext: HttpContext | undefined = options && options.context;
		if (localVarHttpContext === undefined) {
			localVarHttpContext = new HttpContext();
		}

		let localVarTransferCache: boolean | undefined = options && options.transferCache;
		if (localVarTransferCache === undefined) {
			localVarTransferCache = true;
		}

		let responseType_: "text" | "json" | "blob" = "json";
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith("text")) {
				responseType_ = "text";
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = "json";
			} else {
				responseType_ = "blob";
			}
		}

		let localVarPath = `/api/rest/v1/meta/buckets/${this.configuration.encodeParam({
			name: "bucket",
			value: bucket,
			in: "path",
			style: "simple",
			explode: false,
			dataType: "string",
			dataFormat: undefined,
		})}`;
		return this.httpClient.request<ResponseSuccess>("delete", `${this.configuration.basePath}${localVarPath}`, {
			context: localVarHttpContext,
			responseType: <any>responseType_,
			withCredentials: this.configuration.withCredentials,
			headers: localVarHeaders,
			observe: observe,
			transferCache: localVarTransferCache,
			reportProgress: reportProgress,
		});
	}

	/**
	 * @param bucket
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 */
	public getBucket(
		bucket: string,
		observe?: "body",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<Bucket>;
	public getBucket(
		bucket: string,
		observe?: "response",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpResponse<Bucket>>;
	public getBucket(
		bucket: string,
		observe?: "events",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpEvent<Bucket>>;
	public getBucket(
		bucket: string,
		observe: any = "body",
		reportProgress: boolean = false,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<any> {
		if (bucket === null || bucket === undefined) {
			throw new Error("Required parameter bucket was null or undefined when calling getBucket.");
		}

		let localVarHeaders = this.defaultHeaders;

		let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
		if (localVarHttpHeaderAcceptSelected === undefined) {
			// to determine the Accept header
			const httpHeaderAccepts: string[] = ["application/json"];
			localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
		}
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set("Accept", localVarHttpHeaderAcceptSelected);
		}

		let localVarHttpContext: HttpContext | undefined = options && options.context;
		if (localVarHttpContext === undefined) {
			localVarHttpContext = new HttpContext();
		}

		let localVarTransferCache: boolean | undefined = options && options.transferCache;
		if (localVarTransferCache === undefined) {
			localVarTransferCache = true;
		}

		let responseType_: "text" | "json" | "blob" = "json";
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith("text")) {
				responseType_ = "text";
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = "json";
			} else {
				responseType_ = "blob";
			}
		}

		let localVarPath = `/api/rest/v1/meta/buckets/${this.configuration.encodeParam({
			name: "bucket",
			value: bucket,
			in: "path",
			style: "simple",
			explode: false,
			dataType: "string",
			dataFormat: undefined,
		})}`;
		return this.httpClient.request<Bucket>("get", `${this.configuration.basePath}${localVarPath}`, {
			context: localVarHttpContext,
			responseType: <any>responseType_,
			withCredentials: this.configuration.withCredentials,
			headers: localVarHeaders,
			observe: observe,
			transferCache: localVarTransferCache,
			reportProgress: reportProgress,
		});
	}

	/**
	 * @param bucket
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 */
	public getBucketActions(
		bucket: string,
		observe?: "body",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<Array<BucketAction>>;
	public getBucketActions(
		bucket: string,
		observe?: "response",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpResponse<Array<BucketAction>>>;
	public getBucketActions(
		bucket: string,
		observe?: "events",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpEvent<Array<BucketAction>>>;
	public getBucketActions(
		bucket: string,
		observe: any = "body",
		reportProgress: boolean = false,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<any> {
		if (bucket === null || bucket === undefined) {
			throw new Error("Required parameter bucket was null or undefined when calling getBucketActions.");
		}

		let localVarHeaders = this.defaultHeaders;

		let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
		if (localVarHttpHeaderAcceptSelected === undefined) {
			// to determine the Accept header
			const httpHeaderAccepts: string[] = ["application/json"];
			localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
		}
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set("Accept", localVarHttpHeaderAcceptSelected);
		}

		let localVarHttpContext: HttpContext | undefined = options && options.context;
		if (localVarHttpContext === undefined) {
			localVarHttpContext = new HttpContext();
		}

		let localVarTransferCache: boolean | undefined = options && options.transferCache;
		if (localVarTransferCache === undefined) {
			localVarTransferCache = true;
		}

		let responseType_: "text" | "json" | "blob" = "json";
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith("text")) {
				responseType_ = "text";
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = "json";
			} else {
				responseType_ = "blob";
			}
		}

		let localVarPath = `/api/rest/v1/actions/bucket/${this.configuration.encodeParam({
			name: "bucket",
			value: bucket,
			in: "path",
			style: "simple",
			explode: false,
			dataType: "string",
			dataFormat: undefined,
		})}`;
		return this.httpClient.request<Array<BucketAction>>("get", `${this.configuration.basePath}${localVarPath}`, {
			context: localVarHttpContext,
			responseType: <any>responseType_,
			withCredentials: this.configuration.withCredentials,
			headers: localVarHeaders,
			observe: observe,
			transferCache: localVarTransferCache,
			reportProgress: reportProgress,
		});
	}

	/**
	 * @param limit
	 * @param search
	 * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
	 * @param reportProgress flag to report request and response progress.
	 */
	public listBuckets(
		limit?: number,
		search?: string,
		observe?: "body",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<Array<Bucket>>;
	public listBuckets(
		limit?: number,
		search?: string,
		observe?: "response",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpResponse<Array<Bucket>>>;
	public listBuckets(
		limit?: number,
		search?: string,
		observe?: "events",
		reportProgress?: boolean,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<HttpEvent<Array<Bucket>>>;
	public listBuckets(
		limit?: number,
		search?: string,
		observe: any = "body",
		reportProgress: boolean = false,
		options?: { httpHeaderAccept?: "application/json"; context?: HttpContext; transferCache?: boolean }
	): Observable<any> {
		let localVarQueryParameters = new HttpParams({ encoder: this.encoder });
		if (limit !== undefined && limit !== null) {
			localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>limit, "limit");
		}
		if (search !== undefined && search !== null) {
			localVarQueryParameters = this.addToHttpParams(localVarQueryParameters, <any>search, "search");
		}

		let localVarHeaders = this.defaultHeaders;

		let localVarHttpHeaderAcceptSelected: string | undefined = options && options.httpHeaderAccept;
		if (localVarHttpHeaderAcceptSelected === undefined) {
			// to determine the Accept header
			const httpHeaderAccepts: string[] = ["application/json"];
			localVarHttpHeaderAcceptSelected = this.configuration.selectHeaderAccept(httpHeaderAccepts);
		}
		if (localVarHttpHeaderAcceptSelected !== undefined) {
			localVarHeaders = localVarHeaders.set("Accept", localVarHttpHeaderAcceptSelected);
		}

		let localVarHttpContext: HttpContext | undefined = options && options.context;
		if (localVarHttpContext === undefined) {
			localVarHttpContext = new HttpContext();
		}

		let localVarTransferCache: boolean | undefined = options && options.transferCache;
		if (localVarTransferCache === undefined) {
			localVarTransferCache = true;
		}

		let responseType_: "text" | "json" | "blob" = "json";
		if (localVarHttpHeaderAcceptSelected) {
			if (localVarHttpHeaderAcceptSelected.startsWith("text")) {
				responseType_ = "text";
			} else if (this.configuration.isJsonMime(localVarHttpHeaderAcceptSelected)) {
				responseType_ = "json";
			} else {
				responseType_ = "blob";
			}
		}

		let localVarPath = `/api/rest/v1/meta/bucketlist`;
		return this.httpClient.request<Array<Bucket>>("get", `${this.configuration.basePath}${localVarPath}`, {
			context: localVarHttpContext,
			params: localVarQueryParameters,
			responseType: <any>responseType_,
			withCredentials: this.configuration.withCredentials,
			headers: localVarHeaders,
			observe: observe,
			transferCache: localVarTransferCache,
			reportProgress: reportProgress,
		});
	}
}
