export * from './actions.service';
import { ActionsService } from './actions.service';
export * from './authController.service';
import { AuthControllerService } from './authController.service';
export * from './buckets.service';
import { BucketsService } from './buckets.service';
export * from './converter.service';
import { ConverterService } from './converter.service';
export * from './documents.service';
import { DocumentsService } from './documents.service';
export * from './downloads.service';
import { DownloadsService } from './downloads.service';
export * from './filemanager.service';
import { FilemanagerService } from './filemanager.service';
export * from './nodeInfo.service';
import { NodeInfoService } from './nodeInfo.service';
export * from './osgi.service';
import { OsgiService } from './osgi.service';
export * from './pluginmanager.service';
import { PluginmanagerService } from './pluginmanager.service';
export * from './stream.service';
import { StreamService } from './stream.service';
export * from './tagmanager.service';
import { TagmanagerService } from './tagmanager.service';
export * from './tasks.service';
import { TasksService } from './tasks.service';
export * from './transaction.service';
import { TransactionService } from './transaction.service';
export * from './uI.service';
import { UIService } from './uI.service';
export * from './userController.service';
import { UserControllerService } from './userController.service';
export * from './usermanager.service';
import { UsermanagerService } from './usermanager.service';
export const APIS = [ActionsService, AuthControllerService, BucketsService, ConverterService, DocumentsService, DownloadsService, FilemanagerService, NodeInfoService, OsgiService, PluginmanagerService, StreamService, TagmanagerService, TasksService, TransactionService, UIService, UserControllerService, UsermanagerService];
