/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiValueMapStringString
 */
export interface MultiValueMapStringString {
    [key: string]: Array<string> | any;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof MultiValueMapStringString
     */
    all?: { [key: string]: string; };
    /**
     * 
     * @type {boolean}
     * @memberof MultiValueMapStringString
     */
    empty?: boolean;
}

/**
 * Check if a given object implements the MultiValueMapStringString interface.
 */
export function instanceOfMultiValueMapStringString(value: object): value is MultiValueMapStringString {
    return true;
}

export function MultiValueMapStringStringFromJSON(json: any): MultiValueMapStringString {
    return MultiValueMapStringStringFromJSONTyped(json, false);
}

export function MultiValueMapStringStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiValueMapStringString {
    if (json == null) {
        return json;
    }
    return {
        
            ...json,
        'all': json['all'] == null ? undefined : json['all'],
        'empty': json['empty'] == null ? undefined : json['empty'],
    };
}

export function MultiValueMapStringStringToJSON(value?: MultiValueMapStringString | null): any {
    if (value == null) {
        return value;
    }
    return {
        
            ...value,
        'all': value['all'],
        'empty': value['empty'],
    };
}

