/**
 * Mind Plugin Store
 *
 * Contact: info@mind-consulting.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpecModel } from './spec';


export interface PluginModel { 
    id?: string;
    file?: string;
    name?: string;
    pluginId?: string;
    spec?: SpecModel;
}

