/**
 * Mind Plugin Store
 *
 * Contact: info@mind-consulting.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VendorModel { 
    name?: string;
    url?: string;
}

