/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentMetadata } from './documentMetadata';


export interface Document { 
    content_type?: string;
    created?: string;
    last_modified?: string;
    bucket?: string;
    key?: string;
    path?: string;
    etag?: string;
    metadata?: DocumentMetadata;
    owner?: string;
    size?: number;
    version?: string;
    isFolder?: boolean;
}

