const installedPlugins = {
  'mind/ladon-global-dependencies': '2.1.0',
  'mind/ladon-icon-pack': '1.0.0',
  'mind/mf-ladon-auth-api': '1.0.0',
  'mind/mf-ladon-buckets': '1.0.0',
  'mind/mf-ladon-config': '1.4.0',
  'mind/mf-ladon-dashboard': '1.0.1',
  'mind/mf-ladon-docmanager': '1.0.1',
  'mind/mf-ladon-login': '1.2.0',
  'mind/mf-ladon-main-nav': '1.0.3',
  'mind/mf-ladon-plugin': '1.0.0',
  'mind/mf-ladon-share': '1.0.2',
  'mind/mf-ladon-shared-files': '1.0.0',
  'mind/mf-ladon-static-page': '1.1.1',
  'mind/mf-ladon-styles': '1.0.4',
  'mind/mf-ladon-user-manager': '1.3.0',
  'mind/mf-ladon-utility-api': '1.0.1',
  'mind/wc-ladon-pdfviewer': '1.0.1',
  'mind/ladon-webix-docmanager': '0.3.64',
  'mind/wc-ladon-clipboard': '0.5.3',
  'mind/mf-ladon-docmanager-v2': '0.0.5',
  'mind/wc-ladon-meta': '0.3.0',
  'mind/wc-ladon-form': '0.6.1',
};

const channelList = [
  {
    product: 'ladon',
    channel: 'beta',
  },
  {
    product: 'ladon',
    channel: 'stable',
  },
];

const pluginList: any = [
  {
    name: 'Ladon Global Dependencies',
    version: '2.1.0',
    pluginId: 'mind/ladon-global-dependencies',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Global Dependencies',
      channel: ['beta'],
      id: 'mind/ladon-global-dependencies',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/globals/cdn/',
      targetVersion: '4.7.0',
    },
    file: 'globals-2.1.0.tgz',
    id: 'bnBtLXByaXZhdGU6MTNiMjllNDQ5ZjBlM2I4ZDcyZDBiNTQ2M2I2YjY0Mzc',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Config',
    version: '1.4.0',
    pluginId: 'mind/mf-ladon-config',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Config',
      channel: ['stable', 'beta'],
      id: 'mind/mf-ladon-config',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-config-1.4.0.tgz',
    id: 'bnBtLXByaXZhdGU6MTNiMjllNDQ5ZjBlM2I4ZGViYzlhNDNkMjg2ZjljNjI',
    type: 'static-web',
    channel: ['stable', 'beta'],
  },
  {
    name: 'Ladon User Manager',
    version: '1.3.0',
    pluginId: 'mind/mf-ladon-user-manager',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon User Manager',
      channel: ['beta'],
      id: 'mind/mf-ladon-user-manager',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-user-manager',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-user-manager-1.3.0.tgz',
    id: 'bnBtLXByaXZhdGU6ODUxMzU2NTJhOTc4YmU5YTgyMGY2YTM0MjM0NDVjM2M',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Login',
    version: '1.2.0',
    pluginId: 'mind/mf-ladon-login',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Login',
      channel: ['beta'],
      id: 'mind/mf-ladon-login',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-login',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-login-1.2.0.tgz',
    id: 'bnBtLXByaXZhdGU6MGFiODBhNzQzOTIxZTQyNmI4N2UyNDQxMTk3YWVmNWQ',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Auth Api',
    version: '1.0.5',
    pluginId: 'mind/mf-ladon-auth-api',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Auth Api',
      channel: ['beta'],
      id: 'mind/mf-ladon-auth-api',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/api/auth',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-auth-api-1.0.5.tgz',
    id: 'bnBtLXByaXZhdGU6ZDQ4MTE3NTQxZGNiODllYzk0MGQxOWNiMGYyMDMwYmU',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Default Theme',
    version: '1.0.4',
    pluginId: 'mind/mf-ladon-styles',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: 'Standard Style Sheet for Ladon',
      channel: ['beta'],
      name: 'Ladon Default Theme',
      id: 'mind/mf-ladon-styles',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-styles/',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-styles-1.0.4.tgz',
    id: 'bnBtLXByaXZhdGU6ODUxMzU2NTJhOTc4YmU5YWU1ZDVhYzE0YzI5MDIxZDk',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Main Navigation',
    version: '1.0.3',
    pluginId: 'mind/mf-ladon-main-nav',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Main Navigation',
      channel: ['beta'],
      id: 'mind/mf-ladon-main-nav',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-main-nav',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-main-nav-1.0.3.tgz',
    id: 'bnBtLXByaXZhdGU6ZDQ4MTE3NTQxZGNiODllY2Y4ZTBiOWI5M2Q0NDZlZDA',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Share Manager',
    version: '1.0.2',
    pluginId: 'mind/mf-ladon-share',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Share Manager',
      channel: ['beta'],
      id: 'mind/mf-ladon-share',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-share',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-share-1.0.2.tgz',
    id: 'bnBtLXByaXZhdGU6ODUxMzU2NTJhOTc4YmU5YTI4NzYyYTEwOTllNTFkZGI',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Dashboard',
    version: '1.0.1',
    pluginId: 'mind/mf-ladon-dashboard',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Dashboard',
      channel: ['beta'],
      id: 'mind/mf-ladon-dashboard',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-dashboard/',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-dashboard-1.0.1.tgz',
    id: 'bnBtLXByaXZhdGU6MTNiMjllNDQ5ZjBlM2I4ZDhjNTI1Y2U2NmRkMzZmNDE',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon PDFViewer WebComponent',
    version: '1.0.1',
    pluginId: 'mind/wc-ladon-pdfviewer',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: 'This WebComponent allows the user to view PDf Files',
      name: 'Ladon PDFViewer WebComponent',
      channel: ['beta'],
      id: 'mind/wc-ladon-pdfviewer',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-wc/wc-ladon-pdfviewer/',
      targetVersion: '4.7.0',
    },
    file: 'wc-ladon-pdfviewer-1.0.1.tgz',
    id: 'bnBtLXByaXZhdGU6ZDQ4MTE3NTQxZGNiODllYzIwMWYyN2U1MmQ2NjUxOWM',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Utility Api',
    version: '1.0.1',
    pluginId: 'mind/mf-ladon-utility-api',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Utility Api',
      channel: ['beta'],
      id: 'mind/mf-ladon-utility-api',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/api/utility',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-utility-api-1.0.1.tgz',
    id: 'bnBtLXByaXZhdGU6MTNiMjllNDQ5ZjBlM2I4ZDgwMGFlMDVmMGVjZTZiMWE',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Docmanager',
    version: '1.0.1',
    pluginId: 'mind/mf-ladon-docmanager',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Docmanager',
      channel: ['beta'],
      id: 'mind/mf-ladon-docmanager',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-docmanager',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-docmanager-1.0.1.tgz',
    id: 'bnBtLXByaXZhdGU6ODUxMzU2NTJhOTc4YmU5YWYxYTZhMTZkMTc2MzYxOGI',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Buckets',
    version: '1.0.0',
    pluginId: 'mind/mf-ladon-buckets',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Buckets',
      channel: ['beta'],
      id: 'mind/mf-ladon-buckets',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-buckets',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-buckets-1.0.0.tgz',
    id: 'bnBtLXByaXZhdGU6MGFiODBhNzQzOTIxZTQyNjZiM2I1MWRiYmJhZmJlNzU',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Global Dependencies',
    version: '1.0.0',
    pluginId: 'mind/ladon-global-dependencies',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Global Dependencies',
      channel: ['beta'],
      id: 'mind/ladon-global-dependencies',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/globals/cdn/',
      targetVersion: '4.7.0',
    },
    file: 'ladon-global-dependencies-1.0.0.tgz',
    id: 'bnBtLXByaXZhdGU6MTNiMjllNDQ5ZjBlM2I4ZGM3NjNmNWUwYmY2NmExNzg',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Plugin Module',
    version: '1.0.0',
    pluginId: 'mind/mf-ladon-plugin',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.1.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: 'This module allows the user to view and install plugins via the web browser',
      name: 'Ladon Plugin Module',
      channel: ['beta'],
      id: 'mind/mf-ladon-plugin',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/core-mf/mf-ladon-plugin/',
      targetVersion: '4.7.0',
    },
    file: 'mf-ladon-plugin-1.0.0.tgz',
    id: 'bnBtLXByaXZhdGU6ZDQ4MTE3NTQxZGNiODllYzQwMGYyYTcyMjhkZDZlZDI',
    type: 'static-web',
    channel: ['beta'],
  },
  {
    name: 'Ladon Webix Docmanager',
    version: '0.3.64',
    pluginId: 'mind/ladon-webix-docmanager',
    spec: {
      $schema: 'https://plugins.mind-consulting.de/plugin-def-1.0.0.schema.json',
      descriptionFile: 'ladon-plugin.md',
      vendor: {
        name: 'Mind Consulting UG',
        url: 'https://mind-consulting.de',
      },
      shortText: '',
      name: 'Ladon Webix Docmanager',
      id: 'mind/ladon-webix-docmanager',
      type: 'static-web',
      category: ['ui'],
      deployTarget: '/_ui/root/globals/ladondocmanager/',
    },
    file: 'ladon-docmanager-0.3.64.tgz',
    id: 'bnBtLXByaXZhdGU6ODUxMzU2NTJhOTc4YmU5YTk3YzQ4YWUxZDQwMDEzM2M',
    type: 'static-web',
    channel: [],
  },
];

export const pluginTestMock = {
  installedPlugins: installedPlugins,
  channelList: channelList,
  pluginList: pluginList,
};
