/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ConverterInfo, ConverterJob, MultiValueMapStringString } from '../models/index';
import { ConverterInfoFromJSON, ConverterInfoToJSON, ConverterJobFromJSON, ConverterJobToJSON } from '../models/index';

export interface ApplyAndDownloadRequest {
  converterJob: ConverterJob;
}

export interface ApplyAndDownloadGetRequest {
  queryMap: MultiValueMapStringString;
}

export interface ApplyConverterAndStoreRequest {
  converterJob: ConverterJob;
}

/**
 *
 */
export class ConverterApi extends runtime.BaseAPI {
  /**
   */
  async applyAndDownloadRaw(
    requestParameters: ApplyAndDownloadRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Blob>> {
    if (requestParameters['converterJob'] == null) {
      throw new runtime.RequiredError(
        'converterJob',
        'Required parameter "converterJob" was null or undefined when calling applyAndDownload().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/rest/v1/converters/applyanddownload`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ConverterJobToJSON(requestParameters['converterJob']),
      },
      initOverrides,
    );

    return new runtime.BlobApiResponse(response);
  }

  /**
   */
  async applyAndDownload(
    requestParameters: ApplyAndDownloadRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Blob> {
    const response = await this.applyAndDownloadRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async applyAndDownloadGetRaw(
    requestParameters: ApplyAndDownloadGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Blob>> {
    if (requestParameters['queryMap'] == null) {
      throw new runtime.RequiredError(
        'queryMap',
        'Required parameter "queryMap" was null or undefined when calling applyAndDownloadGet().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['queryMap'] != null) {
      queryParameters['queryMap'] = requestParameters['queryMap'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/converters/getdocument`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.BlobApiResponse(response);
  }

  /**
   */
  async applyAndDownloadGet(
    requestParameters: ApplyAndDownloadGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Blob> {
    const response = await this.applyAndDownloadGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async applyConverterAndStoreRaw(
    requestParameters: ApplyConverterAndStoreRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters['converterJob'] == null) {
      throw new runtime.RequiredError(
        'converterJob',
        'Required parameter "converterJob" was null or undefined when calling applyConverterAndStore().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/rest/v1/converters/applyandstore`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: ConverterJobToJSON(requestParameters['converterJob']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async applyConverterAndStore(
    requestParameters: ApplyConverterAndStoreRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.applyConverterAndStoreRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async listConverterInfoRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<ConverterInfo>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/converters/meta`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ConverterInfoFromJSON));
  }

  /**
   */
  async listConverterInfo(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ConverterInfo>> {
    const response = await this.listConverterInfoRaw(initOverrides);
    return await response.value();
  }
}
