/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';

export interface AddTextAsWatermarkGetRequest {
  pdfPath: string;
  text: string;
}

export interface MergePdfDocumentsGetRequest {
  paths: Array<string>;
}

export interface MergePdfDocumentsPostRequest {
  requestBody: Array<string>;
}

export interface ZipDownloadRequest {
  paths: Array<string>;
}

export interface ZipDownloadPostRequest {
  requestBody: Array<string>;
}

export interface ZipUploadRequest {
  bucket: string;
  content?: Blob;
}

/**
 *
 */
export class DownloadsApi extends runtime.BaseAPI {
  /**
   */
  async addTextAsWatermarkGetRaw(
    requestParameters: AddTextAsWatermarkGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters['pdfPath'] == null) {
      throw new runtime.RequiredError(
        'pdfPath',
        'Required parameter "pdfPath" was null or undefined when calling addTextAsWatermarkGet().',
      );
    }

    if (requestParameters['text'] == null) {
      throw new runtime.RequiredError(
        'text',
        'Required parameter "text" was null or undefined when calling addTextAsWatermarkGet().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['pdfPath'] != null) {
      queryParameters['pdfPath'] = requestParameters['pdfPath'];
    }

    if (requestParameters['text'] != null) {
      queryParameters['text'] = requestParameters['text'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/content/addTextAsWatermark`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async addTextAsWatermarkGet(
    requestParameters: AddTextAsWatermarkGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.addTextAsWatermarkGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async mergePdfDocumentsGetRaw(
    requestParameters: MergePdfDocumentsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters['paths'] == null) {
      throw new runtime.RequiredError(
        'paths',
        'Required parameter "paths" was null or undefined when calling mergePdfDocumentsGet().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['paths'] != null) {
      queryParameters['paths'] = requestParameters['paths'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/content/mergepdfdocuments`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async mergePdfDocumentsGet(
    requestParameters: MergePdfDocumentsGetRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.mergePdfDocumentsGetRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async mergePdfDocumentsPostRaw(
    requestParameters: MergePdfDocumentsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: string }>> {
    if (requestParameters['requestBody'] == null) {
      throw new runtime.RequiredError(
        'requestBody',
        'Required parameter "requestBody" was null or undefined when calling mergePdfDocumentsPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/rest/v1/content/mergepdfdocuments`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['requestBody'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async mergePdfDocumentsPost(
    requestParameters: MergePdfDocumentsPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: string }> {
    const response = await this.mergePdfDocumentsPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async zipDownloadRaw(
    requestParameters: ZipDownloadRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters['paths'] == null) {
      throw new runtime.RequiredError(
        'paths',
        'Required parameter "paths" was null or undefined when calling zipDownload().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['paths'] != null) {
      queryParameters['paths'] = requestParameters['paths'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/content/zipdownload`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async zipDownload(
    requestParameters: ZipDownloadRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.zipDownloadRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async zipDownloadPostRaw(
    requestParameters: ZipDownloadPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: string }>> {
    if (requestParameters['requestBody'] == null) {
      throw new runtime.RequiredError(
        'requestBody',
        'Required parameter "requestBody" was null or undefined when calling zipDownloadPost().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/rest/v1/content/zipdownload`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['requestBody'],
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async zipDownloadPost(
    requestParameters: ZipDownloadPostRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: string }> {
    const response = await this.zipDownloadPostRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async zipUploadRaw(
    requestParameters: ZipUploadRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: number }>> {
    if (requestParameters['bucket'] == null) {
      throw new runtime.RequiredError(
        'bucket',
        'Required parameter "bucket" was null or undefined when calling zipUpload().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const consumes: runtime.Consume[] = [{ contentType: 'multipart/form-data' }];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters['content'] != null) {
      formParams.append('content', requestParameters['content'] as any);
    }

    const response = await this.request(
      {
        path: `/api/rest/v1/content/zipupload/{bucket}`.replace(
          `{${'bucket'}}`,
          encodeURIComponent(String(requestParameters['bucket'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async zipUpload(
    requestParameters: ZipUploadRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: number }> {
    const response = await this.zipUploadRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
