/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { ResponseSuccess, TxInfo } from '../models/index';
import { ResponseSuccessFromJSON, ResponseSuccessToJSON, TxInfoFromJSON, TxInfoToJSON } from '../models/index';

export interface CommitTransactionRequest {
  txId: string;
}

export interface RollbackTransactionRequest {
  txId: string;
}

/**
 *
 */
export class TransactionApi extends runtime.BaseAPI {
  /**
   */
  async commitTransactionRaw(
    requestParameters: CommitTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ResponseSuccess>> {
    if (requestParameters['txId'] == null) {
      throw new runtime.RequiredError(
        'txId',
        'Required parameter "txId" was null or undefined when calling commitTransaction().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['txId'] != null) {
      queryParameters['txId'] = requestParameters['txId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/transaction/commit`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSuccessFromJSON(jsonValue));
  }

  /**
   */
  async commitTransaction(
    requestParameters: CommitTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ResponseSuccess> {
    const response = await this.commitTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async isTxActiveRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<boolean>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/transaction/active`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    if (this.isJsonMime(response.headers.get('content-type'))) {
      return new runtime.JSONApiResponse<boolean>(response);
    } else {
      return new runtime.TextApiResponse(response) as any;
    }
  }

  /**
   */
  async isTxActive(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<boolean> {
    const response = await this.isTxActiveRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async rollbackTransactionRaw(
    requestParameters: RollbackTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<ResponseSuccess>> {
    if (requestParameters['txId'] == null) {
      throw new runtime.RequiredError(
        'txId',
        'Required parameter "txId" was null or undefined when calling rollbackTransaction().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['txId'] != null) {
      queryParameters['txId'] = requestParameters['txId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/transaction/rollback`,
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => ResponseSuccessFromJSON(jsonValue));
  }

  /**
   */
  async rollbackTransaction(
    requestParameters: RollbackTransactionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<ResponseSuccess> {
    const response = await this.rollbackTransactionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async startTransactionRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<TxInfo>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/rest/v1/transaction/start`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => TxInfoFromJSON(jsonValue));
  }

  /**
   */
  async startTransaction(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<TxInfo> {
    const response = await this.startTransactionRaw(initOverrides);
    return await response.value();
  }
}
