/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { User } from '../models/index';
import { UserFromJSON, UserToJSON } from '../models/index';

export interface GetPictureRequest {
  userId: string;
}

/**
 *
 */
export class UsersApi extends runtime.BaseAPI {
  /**
   */
  async getAllowableActionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: object }>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/user/allowableactions`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async getAllowableActions(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: object }> {
    const response = await this.getAllowableActionsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getCurrentUserRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<User>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/user/me`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserFromJSON(jsonValue));
  }

  /**
   */
  async getCurrentUser(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<User> {
    const response = await this.getCurrentUserRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getPictureRaw(
    requestParameters: GetPictureRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getPicture().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/user/{userId}/picture`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async getPicture(
    requestParameters: GetPictureRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.getPictureRaw(requestParameters, initOverrides);
    return await response.value();
  }
}
