/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type {
  CredentialsWrapper,
  LadonPermission,
  Permission,
  RoleEntry,
  RoleWrapper,
  UserDataWrapper,
  UserEntry,
  UserLogins,
  UserWrapper,
} from '../models/index';
import {
  CredentialsWrapperFromJSON,
  CredentialsWrapperToJSON,
  LadonPermissionFromJSON,
  LadonPermissionToJSON,
  PermissionFromJSON,
  PermissionToJSON,
  RoleEntryFromJSON,
  RoleEntryToJSON,
  RoleWrapperFromJSON,
  RoleWrapperToJSON,
  UserDataWrapperFromJSON,
  UserDataWrapperToJSON,
  UserEntryFromJSON,
  UserEntryToJSON,
  UserLoginsFromJSON,
  UserLoginsToJSON,
  UserWrapperFromJSON,
  UserWrapperToJSON,
} from '../models/index';

export interface AddAvatarRequest {
  userId: string;
  uploadFullpath: string;
  upload: Blob;
}

export interface AddPermissionForRoleRequest {
  roleId: string;
  permissionId: string;
}

export interface AddPermissionForUserRequest {
  userId: string;
  permissionId: string;
}

export interface AddRoleForUserRequest {
  userId: string;
  roleId: string;
}

export interface AddUserRequest {
  userWrapper: UserWrapper;
}

export interface CreatePermissionsRequest {
  ladonPermission: LadonPermission;
}

export interface CreateRoleRequest {
  roleWrapper: RoleWrapper;
}

export interface DeleteRoleRequest {
  roleId: string;
}

export interface DeleteRoleForUserRequest {
  userId: string;
  roleId: string;
}

export interface DeleteUserRequest {
  userId: string;
}

export interface GetLoginLogsRequest {
  userId: string;
}

export interface GetPermissionsForRoleRequest {
  roleId: string;
}

export interface GetPermissionsForUserRequest {
  userId: string;
}

export interface GetRoleForUserRequest {
  userId: string;
}

export interface GetUserDataRequest {
  userId: string;
}

export interface GetUsersForRoleRequest {
  roleId: string;
}

export interface RemovePermissionRequest {
  permissionId: string;
}

export interface RemovePermissionFromRoleRequest {
  roleId: string;
  permissionId: string;
}

export interface RemovePermissionFromUserRequest {
  userId: string;
  permissionId: string;
}

export interface SetCredentialsRequest {
  userId: string;
  body: string;
}

export interface UpdateCredentialsRequest {
  userId: string;
  credentialsWrapper: CredentialsWrapper;
}

export interface UpdateUserRequest {
  userId: string;
  userDataWrapper: UserDataWrapper;
}

/**
 *
 */
export class UsermanagerApi extends runtime.BaseAPI {
  /**
   */
  async addAvatarRaw(
    requestParameters: AddAvatarRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling addAvatar().',
      );
    }

    if (requestParameters['uploadFullpath'] == null) {
      throw new runtime.RequiredError(
        'uploadFullpath',
        'Required parameter "uploadFullpath" was null or undefined when calling addAvatar().',
      );
    }

    if (requestParameters['upload'] == null) {
      throw new runtime.RequiredError(
        'upload',
        'Required parameter "upload" was null or undefined when calling addAvatar().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['uploadFullpath'] != null) {
      queryParameters['upload_fullpath'] = requestParameters['uploadFullpath'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const consumes: runtime.Consume[] = [{ contentType: 'multipart/form-data' }];
    // @ts-ignore: canConsumeForm may be unused
    const canConsumeForm = runtime.canConsumeForm(consumes);

    let formParams: { append(param: string, value: any): any };
    let useForm = false;
    // use FormData to transmit files using content-type "multipart/form-data"
    useForm = canConsumeForm;
    if (useForm) {
      formParams = new FormData();
    } else {
      formParams = new URLSearchParams();
    }

    if (requestParameters['upload'] != null) {
      formParams.append('upload', requestParameters['upload'] as any);
    }

    const response = await this.request(
      {
        path: `/api/usermanager/users/{userId}/avatar`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: formParams,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addAvatar(
    requestParameters: AddAvatarRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addAvatarRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addPermissionForRoleRaw(
    requestParameters: AddPermissionForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['roleId'] == null) {
      throw new runtime.RequiredError(
        'roleId',
        'Required parameter "roleId" was null or undefined when calling addPermissionForRole().',
      );
    }

    if (requestParameters['permissionId'] == null) {
      throw new runtime.RequiredError(
        'permissionId',
        'Required parameter "permissionId" was null or undefined when calling addPermissionForRole().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['permissionId'] != null) {
      queryParameters['permissionId'] = requestParameters['permissionId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/role/{roleId}`.replace(
          `{${'roleId'}}`,
          encodeURIComponent(String(requestParameters['roleId'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addPermissionForRole(
    requestParameters: AddPermissionForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addPermissionForRoleRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addPermissionForUserRaw(
    requestParameters: AddPermissionForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling addPermissionForUser().',
      );
    }

    if (requestParameters['permissionId'] == null) {
      throw new runtime.RequiredError(
        'permissionId',
        'Required parameter "permissionId" was null or undefined when calling addPermissionForUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['permissionId'] != null) {
      queryParameters['permissionId'] = requestParameters['permissionId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/user/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addPermissionForUser(
    requestParameters: AddPermissionForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addPermissionForUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addRoleForUserRaw(
    requestParameters: AddRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling addRoleForUser().',
      );
    }

    if (requestParameters['roleId'] == null) {
      throw new runtime.RequiredError(
        'roleId',
        'Required parameter "roleId" was null or undefined when calling addRoleForUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['roleId'] != null) {
      queryParameters['roleId'] = requestParameters['roleId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles/user/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async addRoleForUser(
    requestParameters: AddRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.addRoleForUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async addUserRaw(
    requestParameters: AddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<{ [key: string]: string }>> {
    if (requestParameters['userWrapper'] == null) {
      throw new runtime.RequiredError(
        'userWrapper',
        'Required parameter "userWrapper" was null or undefined when calling addUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/usermanager/users`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: UserWrapperToJSON(requestParameters['userWrapper']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async addUser(
    requestParameters: AddUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<{ [key: string]: string }> {
    const response = await this.addUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async createPermissionsRaw(
    requestParameters: CreatePermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters['ladonPermission'] == null) {
      throw new runtime.RequiredError(
        'ladonPermission',
        'Required parameter "ladonPermission" was null or undefined when calling createPermissions().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/usermanager/permissions`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: LadonPermissionToJSON(requestParameters['ladonPermission']),
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async createPermissions(
    requestParameters: CreatePermissionsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.createPermissionsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async createRoleRaw(
    requestParameters: CreateRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['roleWrapper'] == null) {
      throw new runtime.RequiredError(
        'roleWrapper',
        'Required parameter "roleWrapper" was null or undefined when calling createRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/usermanager/roles`,
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: RoleWrapperToJSON(requestParameters['roleWrapper']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async createRole(
    requestParameters: CreateRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.createRoleRaw(requestParameters, initOverrides);
  }

  /**
   */
  async deleteRoleRaw(
    requestParameters: DeleteRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['roleId'] == null) {
      throw new runtime.RequiredError(
        'roleId',
        'Required parameter "roleId" was null or undefined when calling deleteRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles/{roleId}`.replace(
          `{${'roleId'}}`,
          encodeURIComponent(String(requestParameters['roleId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteRole(
    requestParameters: DeleteRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteRoleRaw(requestParameters, initOverrides);
  }

  /**
   */
  async deleteRoleForUserRaw(
    requestParameters: DeleteRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling deleteRoleForUser().',
      );
    }

    if (requestParameters['roleId'] == null) {
      throw new runtime.RequiredError(
        'roleId',
        'Required parameter "roleId" was null or undefined when calling deleteRoleForUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['roleId'] != null) {
      queryParameters['roleId'] = requestParameters['roleId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles/user/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteRoleForUser(
    requestParameters: DeleteRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteRoleForUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async deleteUserRaw(
    requestParameters: DeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling deleteUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/users/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async deleteUser(
    requestParameters: DeleteUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.deleteUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async getAllPermissionsRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PermissionFromJSON));
  }

  /**
   */
  async getAllPermissions(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Permission>> {
    const response = await this.getAllPermissionsRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getLoginLogsRaw(
    requestParameters: GetLoginLogsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<UserLogins>>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getLoginLogs().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/logs/login/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserLoginsFromJSON));
  }

  /**
   */
  async getLoginLogs(
    requestParameters: GetLoginLogsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<UserLogins>> {
    const response = await this.getLoginLogsRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async getPermissionsForRoleRaw(
    requestParameters: GetPermissionsForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>> {
    if (requestParameters['roleId'] == null) {
      throw new runtime.RequiredError(
        'roleId',
        'Required parameter "roleId" was null or undefined when calling getPermissionsForRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/role/{roleId}`.replace(
          `{${'roleId'}}`,
          encodeURIComponent(String(requestParameters['roleId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PermissionFromJSON));
  }

  /**
   */
  async getPermissionsForRole(
    requestParameters: GetPermissionsForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Permission>> {
    const response = await this.getPermissionsForRoleRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async getPermissionsForUserRaw(
    requestParameters: GetPermissionsForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<Permission>>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getPermissionsForUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/user/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PermissionFromJSON));
  }

  /**
   */
  async getPermissionsForUser(
    requestParameters: GetPermissionsForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<Permission>> {
    const response = await this.getPermissionsForUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async getRoleForUserRaw(
    requestParameters: GetRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getRoleForUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles/user/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async getRoleForUser(
    requestParameters: GetRoleForUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.getRoleForUserRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async getRolesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<RoleEntry>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/roles`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(RoleEntryFromJSON));
  }

  /**
   */
  async getRoles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<RoleEntry>> {
    const response = await this.getRolesRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getUserDataRaw(
    requestParameters: GetUserDataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<UserDataWrapper>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling getUserData().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/users/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => UserDataWrapperFromJSON(jsonValue));
  }

  /**
   */
  async getUserData(
    requestParameters: GetUserDataRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<UserDataWrapper> {
    const response = await this.getUserDataRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async getUsersRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<UserEntry>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/users`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(UserEntryFromJSON));
  }

  /**
   */
  async getUsers(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<UserEntry>> {
    const response = await this.getUsersRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getUsersForRoleRaw(
    requestParameters: GetUsersForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<string>>> {
    if (requestParameters['roleId'] == null) {
      throw new runtime.RequiredError(
        'roleId',
        'Required parameter "roleId" was null or undefined when calling getUsersForRole().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/users/role/{roleId}`.replace(
          `{${'roleId'}}`,
          encodeURIComponent(String(requestParameters['roleId'])),
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async getUsersForRole(
    requestParameters: GetUsersForRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<string>> {
    const response = await this.getUsersForRoleRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async removePermissionRaw(
    requestParameters: RemovePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<object>> {
    if (requestParameters['permissionId'] == null) {
      throw new runtime.RequiredError(
        'permissionId',
        'Required parameter "permissionId" was null or undefined when calling removePermission().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/{permissionId}`.replace(
          `{${'permissionId'}}`,
          encodeURIComponent(String(requestParameters['permissionId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse<any>(response);
  }

  /**
   */
  async removePermission(
    requestParameters: RemovePermissionRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<object> {
    const response = await this.removePermissionRaw(requestParameters, initOverrides);
    return await response.value();
  }

  /**
   */
  async removePermissionFromRoleRaw(
    requestParameters: RemovePermissionFromRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['roleId'] == null) {
      throw new runtime.RequiredError(
        'roleId',
        'Required parameter "roleId" was null or undefined when calling removePermissionFromRole().',
      );
    }

    if (requestParameters['permissionId'] == null) {
      throw new runtime.RequiredError(
        'permissionId',
        'Required parameter "permissionId" was null or undefined when calling removePermissionFromRole().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['permissionId'] != null) {
      queryParameters['permissionId'] = requestParameters['permissionId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/role/{roleId}`.replace(
          `{${'roleId'}}`,
          encodeURIComponent(String(requestParameters['roleId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async removePermissionFromRole(
    requestParameters: RemovePermissionFromRoleRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removePermissionFromRoleRaw(requestParameters, initOverrides);
  }

  /**
   */
  async removePermissionFromUserRaw(
    requestParameters: RemovePermissionFromUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling removePermissionFromUser().',
      );
    }

    if (requestParameters['permissionId'] == null) {
      throw new runtime.RequiredError(
        'permissionId',
        'Required parameter "permissionId" was null or undefined when calling removePermissionFromUser().',
      );
    }

    const queryParameters: any = {};

    if (requestParameters['permissionId'] != null) {
      queryParameters['permissionId'] = requestParameters['permissionId'];
    }

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/api/usermanager/permissions/user/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'DELETE',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async removePermissionFromUser(
    requestParameters: RemovePermissionFromUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.removePermissionFromUserRaw(requestParameters, initOverrides);
  }

  /**
   */
  async setCredentialsRaw(
    requestParameters: SetCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling setCredentials().',
      );
    }

    if (requestParameters['body'] == null) {
      throw new runtime.RequiredError(
        'body',
        'Required parameter "body" was null or undefined when calling setCredentials().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/usermanager/user/{userId}/credentials`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'POST',
        headers: headerParameters,
        query: queryParameters,
        body: requestParameters['body'] as any,
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async setCredentials(
    requestParameters: SetCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.setCredentialsRaw(requestParameters, initOverrides);
  }

  /**
   */
  async updateCredentialsRaw(
    requestParameters: UpdateCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling updateCredentials().',
      );
    }

    if (requestParameters['credentialsWrapper'] == null) {
      throw new runtime.RequiredError(
        'credentialsWrapper',
        'Required parameter "credentialsWrapper" was null or undefined when calling updateCredentials().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/usermanager/user/{userId}/credentials`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: CredentialsWrapperToJSON(requestParameters['credentialsWrapper']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async updateCredentials(
    requestParameters: UpdateCredentialsRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.updateCredentialsRaw(requestParameters, initOverrides);
  }

  /**
   */
  async updateUserRaw(
    requestParameters: UpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<void>> {
    if (requestParameters['userId'] == null) {
      throw new runtime.RequiredError(
        'userId',
        'Required parameter "userId" was null or undefined when calling updateUser().',
      );
    }

    if (requestParameters['userDataWrapper'] == null) {
      throw new runtime.RequiredError(
        'userDataWrapper',
        'Required parameter "userDataWrapper" was null or undefined when calling updateUser().',
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters['Content-Type'] = 'application/json';

    const response = await this.request(
      {
        path: `/api/usermanager/users/{userId}`.replace(
          `{${'userId'}}`,
          encodeURIComponent(String(requestParameters['userId'])),
        ),
        method: 'PUT',
        headers: headerParameters,
        query: queryParameters,
        body: UserDataWrapperToJSON(requestParameters['userDataWrapper']),
      },
      initOverrides,
    );

    return new runtime.VoidApiResponse(response);
  }

  /**
   */
  async updateUser(
    requestParameters: UpdateUserRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<void> {
    await this.updateUserRaw(requestParameters, initOverrides);
  }
}
