/**
 * Ladon Datacenter Edition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface BucketUiItemModel { 
    id?: string;
    createdBy?: string;
    size?: number;
    versioned?: boolean;
    favourite?: boolean;
    created?: string;
    createdDate?: number;
}

