/**
 * Ladon Datacenter Edition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StatisticsModel } from "./statistics";

export interface BucketStatisticsModel {
  bucketid: string;
  statistics: StatisticsModel;
}
