/**
 * Ladon Datacenter Edition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface ChangeModel {
  bucket: string;
  key: string;
  version: string;
  op: ChangeModel.OpEnum;
  userId: string;
  unixTimestamp: number;
}
export namespace ChangeModel {
  export type OpEnum = "PUT" | "DELETE";
  export const OpEnum = {
    Put: "PUT" as OpEnum,
    Delete: "DELETE" as OpEnum,
  };
}
