/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BucketUiItem
 */
export interface BucketUiItem {
    /**
     * 
     * @type {string}
     * @memberof BucketUiItem
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof BucketUiItem
     */
    createdBy?: string;
    /**
     * 
     * @type {number}
     * @memberof BucketUiItem
     */
    size?: number;
    /**
     * 
     * @type {boolean}
     * @memberof BucketUiItem
     */
    versioned?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof BucketUiItem
     */
    favourite?: boolean;
    /**
     * 
     * @type {string}
     * @memberof BucketUiItem
     */
    created?: string;
    /**
     * 
     * @type {number}
     * @memberof BucketUiItem
     */
    createdDate?: number;
}

/**
 * Check if a given object implements the BucketUiItem interface.
 */
export function instanceOfBucketUiItem(value: object): value is BucketUiItem {
    return true;
}

export function BucketUiItemFromJSON(json: any): BucketUiItem {
    return BucketUiItemFromJSONTyped(json, false);
}

export function BucketUiItemFromJSONTyped(json: any, ignoreDiscriminator: boolean): BucketUiItem {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'createdBy': json['createdBy'] == null ? undefined : json['createdBy'],
        'size': json['size'] == null ? undefined : json['size'],
        'versioned': json['versioned'] == null ? undefined : json['versioned'],
        'favourite': json['favourite'] == null ? undefined : json['favourite'],
        'created': json['created'] == null ? undefined : json['created'],
        'createdDate': json['createdDate'] == null ? undefined : json['createdDate'],
    };
}

export function BucketUiItemToJSON(json: any): BucketUiItem {
    return BucketUiItemToJSONTyped(json, false);
}

export function BucketUiItemToJSONTyped(value?: BucketUiItem | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'createdBy': value['createdBy'],
        'size': value['size'],
        'versioned': value['versioned'],
        'favourite': value['favourite'],
        'created': value['created'],
        'createdDate': value['createdDate'],
    };
}

