/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface Bucket
 */
export interface Bucket {
  /**
   *
   * @type {string}
   * @memberof Bucket
   */
  created?: string;
  /**
   *
   * @type {string}
   * @memberof Bucket
   */
  name?: string;
  /**
   *
   * @type {string}
   * @memberof Bucket
   */
  owner?: string;
  /**
   *
   * @type {boolean}
   * @memberof Bucket
   */
  versioned?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Bucket
   */
  virtual?: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Bucket
   */
  indexed?: boolean;
}

/**
 * Check if a given object implements the Bucket interface.
 */
export function instanceOfBucket(value: object): value is Bucket {
  return true;
}

export function BucketFromJSON(json: any): Bucket {
  return BucketFromJSONTyped(json, false);
}

export function BucketFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): Bucket {
  if (json == null) {
    return json;
  }
  return {
    created: json["created"] == null ? undefined : json["created"],
    name: json["name"] == null ? undefined : json["name"],
    owner: json["owner"] == null ? undefined : json["owner"],
    versioned: json["versioned"] == null ? undefined : json["versioned"],
    virtual: json["virtual"] == null ? undefined : json["virtual"],
    indexed: json["indexed"] == null ? undefined : json["indexed"],
  };
}

export function BucketToJSON(json: any): Bucket {
  return BucketToJSONTyped(json, false);
}

export function BucketToJSONTyped(
  value?: Bucket | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    created: value["created"],
    name: value["name"],
    owner: value["owner"],
    versioned: value["versioned"],
    virtual: value["virtual"],
    indexed: value["indexed"],
  };
}
