/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Change
 */
export interface Change {
    /**
     * 
     * @type {string}
     * @memberof Change
     */
    bucket: string;
    /**
     * 
     * @type {string}
     * @memberof Change
     */
    key: string;
    /**
     * 
     * @type {string}
     * @memberof Change
     */
    version: string;
    /**
     * 
     * @type {string}
     * @memberof Change
     */
    op: ChangeOpEnum;
    /**
     * 
     * @type {string}
     * @memberof Change
     */
    userId: string;
    /**
     * 
     * @type {number}
     * @memberof Change
     */
    unixTimestamp: number;
}


/**
 * @export
 */
export const ChangeOpEnum = {
    Put: 'PUT',
    Delete: 'DELETE'
} as const;
export type ChangeOpEnum = typeof ChangeOpEnum[keyof typeof ChangeOpEnum];


/**
 * Check if a given object implements the Change interface.
 */
export function instanceOfChange(value: object): value is Change {
    if (!('bucket' in value) || value['bucket'] === undefined) return false;
    if (!('key' in value) || value['key'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('op' in value) || value['op'] === undefined) return false;
    if (!('userId' in value) || value['userId'] === undefined) return false;
    if (!('unixTimestamp' in value) || value['unixTimestamp'] === undefined) return false;
    return true;
}

export function ChangeFromJSON(json: any): Change {
    return ChangeFromJSONTyped(json, false);
}

export function ChangeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Change {
    if (json == null) {
        return json;
    }
    return {
        
        'bucket': json['bucket'],
        'key': json['key'],
        'version': json['version'],
        'op': json['op'],
        'userId': json['userId'],
        'unixTimestamp': json['unixTimestamp'],
    };
}

export function ChangeToJSON(json: any): Change {
    return ChangeToJSONTyped(json, false);
}

export function ChangeToJSONTyped(value?: Change | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bucket': value['bucket'],
        'key': value['key'],
        'version': value['version'],
        'op': value['op'],
        'userId': value['userId'],
        'unixTimestamp': value['unixTimestamp'],
    };
}

