/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConverterConfig
 */
export interface ConverterConfig {
    /**
     * 
     * @type {string}
     * @memberof ConverterConfig
     */
    id: string;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof ConverterConfig
     */
    config: { [key: string]: string; };
}

/**
 * Check if a given object implements the ConverterConfig interface.
 */
export function instanceOfConverterConfig(value: object): value is ConverterConfig {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('config' in value) || value['config'] === undefined) return false;
    return true;
}

export function ConverterConfigFromJSON(json: any): ConverterConfig {
    return ConverterConfigFromJSONTyped(json, false);
}

export function ConverterConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConverterConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'config': json['config'],
    };
}

export function ConverterConfigToJSON(json: any): ConverterConfig {
    return ConverterConfigToJSONTyped(json, false);
}

export function ConverterConfigToJSONTyped(value?: ConverterConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'config': value['config'],
    };
}

