/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DocumentAction
 */
export interface DocumentAction {
    /**
     * 
     * @type {string}
     * @memberof DocumentAction
     */
    i18nName?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentAction
     */
    label?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentAction
     */
    actionId?: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentAction
     */
    icon?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof DocumentAction
     */
    input?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof DocumentAction
     */
    target?: string;
}

/**
 * Check if a given object implements the DocumentAction interface.
 */
export function instanceOfDocumentAction(value: object): value is DocumentAction {
    return true;
}

export function DocumentActionFromJSON(json: any): DocumentAction {
    return DocumentActionFromJSONTyped(json, false);
}

export function DocumentActionFromJSONTyped(json: any, ignoreDiscriminator: boolean): DocumentAction {
    if (json == null) {
        return json;
    }
    return {
        
        'i18nName': json['i18nName'] == null ? undefined : json['i18nName'],
        'label': json['label'] == null ? undefined : json['label'],
        'actionId': json['actionId'] == null ? undefined : json['actionId'],
        'icon': json['icon'] == null ? undefined : json['icon'],
        'input': json['input'] == null ? undefined : json['input'],
        'target': json['target'] == null ? undefined : json['target'],
    };
}

export function DocumentActionToJSON(json: any): DocumentAction {
    return DocumentActionToJSONTyped(json, false);
}

export function DocumentActionToJSONTyped(value?: DocumentAction | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'i18nName': value['i18nName'],
        'label': value['label'],
        'actionId': value['actionId'],
        'icon': value['icon'],
        'input': value['input'],
        'target': value['target'],
    };
}

