/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Meta } from './Meta';
import {
    MetaFromJSON,
    MetaFromJSONTyped,
    MetaToJSON,
    MetaToJSONTyped,
} from './Meta';
import type { Preview } from './Preview';
import {
    PreviewFromJSON,
    PreviewFromJSONTyped,
    PreviewToJSON,
    PreviewToJSONTyped,
} from './Preview';

/**
 * 
 * @export
 * @interface Features
 */
export interface Features {
    /**
     * 
     * @type {Preview}
     * @memberof Features
     */
    preview: Preview;
    /**
     * 
     * @type {Meta}
     * @memberof Features
     */
    meta: Meta;
}

/**
 * Check if a given object implements the Features interface.
 */
export function instanceOfFeatures(value: object): value is Features {
    if (!('preview' in value) || value['preview'] === undefined) return false;
    if (!('meta' in value) || value['meta'] === undefined) return false;
    return true;
}

export function FeaturesFromJSON(json: any): Features {
    return FeaturesFromJSONTyped(json, false);
}

export function FeaturesFromJSONTyped(json: any, ignoreDiscriminator: boolean): Features {
    if (json == null) {
        return json;
    }
    return {
        
        'preview': PreviewFromJSON(json['preview']),
        'meta': MetaFromJSON(json['meta']),
    };
}

export function FeaturesToJSON(json: any): Features {
    return FeaturesToJSONTyped(json, false);
}

export function FeaturesToJSONTyped(value?: Features | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'preview': PreviewToJSON(value['preview']),
        'meta': MetaToJSON(value['meta']),
    };
}

