/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Stats } from './Stats';
import {
    StatsFromJSON,
    StatsFromJSONTyped,
    StatsToJSON,
    StatsToJSONTyped,
} from './Stats';
import type { Features } from './Features';
import {
    FeaturesFromJSON,
    FeaturesFromJSONTyped,
    FeaturesToJSON,
    FeaturesToJSONTyped,
} from './Features';

/**
 * 
 * @export
 * @interface Info
 */
export interface Info {
    /**
     * 
     * @type {Stats}
     * @memberof Info
     */
    stats: Stats;
    /**
     * 
     * @type {Features}
     * @memberof Info
     */
    features: Features;
}

/**
 * Check if a given object implements the Info interface.
 */
export function instanceOfInfo(value: object): value is Info {
    if (!('stats' in value) || value['stats'] === undefined) return false;
    if (!('features' in value) || value['features'] === undefined) return false;
    return true;
}

export function InfoFromJSON(json: any): Info {
    return InfoFromJSONTyped(json, false);
}

export function InfoFromJSONTyped(json: any, ignoreDiscriminator: boolean): Info {
    if (json == null) {
        return json;
    }
    return {
        
        'stats': StatsFromJSON(json['stats']),
        'features': FeaturesFromJSON(json['features']),
    };
}

export function InfoToJSON(json: any): Info {
    return InfoToJSONTyped(json, false);
}

export function InfoToJSONTyped(value?: Info | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'stats': StatsToJSON(value['stats']),
        'features': FeaturesToJSON(value['features']),
    };
}

