/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface NewBucket
 */
export interface NewBucket {
  /**
   *
   * @type {string}
   * @memberof NewBucket
   */
  bucketid?: string;
  /**
   *
   * @type {string}
   * @memberof NewBucket
   */
  versioned?: string;
  /**
   *
   * @type {string}
   * @memberof NewBucket
   */
  favourite?: string;
  /**
   *
   * @type {string}
   * @memberof NewBucket
   */
  storageId?: string;
  /**
   *
   * @type {string}
   * @memberof NewBucket
   */
  webixOperation?: string;
}

/**
 * Check if a given object implements the NewBucket interface.
 */
export function instanceOfNewBucket(value: object): value is NewBucket {
  return true;
}

export function NewBucketFromJSON(json: any): NewBucket {
  return NewBucketFromJSONTyped(json, false);
}

export function NewBucketFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): NewBucket {
  if (json == null) {
    return json;
  }
  return {
    bucketid: json["bucketid"] == null ? undefined : json["bucketid"],
    versioned: json["versioned"] == null ? undefined : json["versioned"],
    favourite: json["favourite"] == null ? undefined : json["favourite"],
    storageId: json["storageId"] == null ? undefined : json["storageId"],
    webixOperation:
      json["webix_operation"] == null ? undefined : json["webix_operation"],
  };
}

export function NewBucketToJSON(json: any): NewBucket {
  return NewBucketToJSONTyped(json, false);
}

export function NewBucketToJSONTyped(
  value?: NewBucket | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    bucketid: value["bucketid"],
    versioned: value["versioned"],
    favourite: value["favourite"],
    storageId: value["storageId"],
    webix_operation: value["webixOperation"],
  };
}
