/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface ResponseSuccess
 */
export interface ResponseSuccess {
  /**
   *
   * @type {boolean}
   * @memberof ResponseSuccess
   */
  success: boolean;
  /**
   *
   * @type {string}
   * @memberof ResponseSuccess
   */
  reason?: string;
}

/**
 * Check if a given object implements the ResponseSuccess interface.
 */
export function instanceOfResponseSuccess(
  value: object,
): value is ResponseSuccess {
  if (!("success" in value) || value["success"] === undefined) return false;
  return true;
}

export function ResponseSuccessFromJSON(json: any): ResponseSuccess {
  return ResponseSuccessFromJSONTyped(json, false);
}

export function ResponseSuccessFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): ResponseSuccess {
  if (json == null) {
    return json;
  }
  return {
    success: json["success"],
    reason: json["reason"] == null ? undefined : json["reason"],
  };
}

export function ResponseSuccessToJSON(json: any): ResponseSuccess {
  return ResponseSuccessToJSONTyped(json, false);
}

export function ResponseSuccessToJSONTyped(
  value?: ResponseSuccess | null,
  ignoreDiscriminator: boolean = false,
): any {
  if (value == null) {
    return value;
  }

  return {
    success: value["success"],
    reason: value["reason"],
  };
}
