/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ShareDataInput
 */
export interface ShareDataInput {
    /**
     * 
     * @type {string}
     * @memberof ShareDataInput
     */
    title: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof ShareDataInput
     */
    selection: Array<string>;
    /**
     * 
     * @type {Date}
     * @memberof ShareDataInput
     */
    validDate?: Date;
    /**
     * 
     * @type {string}
     * @memberof ShareDataInput
     */
    password?: string;
    /**
     * 
     * @type {string}
     * @memberof ShareDataInput
     */
    recipient?: string;
}

/**
 * Check if a given object implements the ShareDataInput interface.
 */
export function instanceOfShareDataInput(value: object): value is ShareDataInput {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('selection' in value) || value['selection'] === undefined) return false;
    return true;
}

export function ShareDataInputFromJSON(json: any): ShareDataInput {
    return ShareDataInputFromJSONTyped(json, false);
}

export function ShareDataInputFromJSONTyped(json: any, ignoreDiscriminator: boolean): ShareDataInput {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'selection': json['selection'],
        'validDate': json['validDate'] == null ? undefined : (new Date(json['validDate'])),
        'password': json['password'] == null ? undefined : json['password'],
        'recipient': json['recipient'] == null ? undefined : json['recipient'],
    };
}

export function ShareDataInputToJSON(json: any): ShareDataInput {
    return ShareDataInputToJSONTyped(json, false);
}

export function ShareDataInputToJSONTyped(value?: ShareDataInput | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'title': value['title'],
        'selection': value['selection'],
        'validDate': value['validDate'] == null ? undefined : ((value['validDate']).toISOString()),
        'password': value['password'],
        'recipient': value['recipient'],
    };
}

