/* tslint:disable */
/* eslint-disable */
/**
 * Ladon Datacenter Edition
 * Ladon Datacenter Edition REST API
 *
 * The version of the OpenAPI document: 5.3.21
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Stats
 */
export interface Stats {
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    free: number;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    used: number;
    /**
     * 
     * @type {number}
     * @memberof Stats
     */
    total: number;
}

/**
 * Check if a given object implements the Stats interface.
 */
export function instanceOfStats(value: object): value is Stats {
    if (!('free' in value) || value['free'] === undefined) return false;
    if (!('used' in value) || value['used'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function StatsFromJSON(json: any): Stats {
    return StatsFromJSONTyped(json, false);
}

export function StatsFromJSONTyped(json: any, ignoreDiscriminator: boolean): Stats {
    if (json == null) {
        return json;
    }
    return {
        
        'free': json['free'],
        'used': json['used'],
        'total': json['total'],
    };
}

export function StatsToJSON(json: any): Stats {
    return StatsToJSONTyped(json, false);
}

export function StatsToJSONTyped(value?: Stats | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'free': value['free'],
        'used': value['used'],
        'total': value['total'],
    };
}

