/**
 * Ladon Datacenter Edition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface AllBucketStatsModel {
  size?: number;
  versions?: number;
  files?: number;
  folders?: number;
}
