/**
 * Ladon Datacenter Edition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BucketModel } from './bucket';

export interface CreateBucketRequestModel {
  storageId?: string;
  body?: BucketModel;
}
