/**
 * Ladon Datacenter Edition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DataResponseModel { 
    id: string;
    newid: string;
    status: DataResponseModel.StatusEnum;
}
export namespace DataResponseModel {
    export type StatusEnum = 'error' | 'success';
    export const StatusEnum = {
        Error: 'error' as StatusEnum,
        Success: 'success' as StatusEnum
    };
}


