/**
 * Ladon Datacenter Edition
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentMetadataModel } from './documentMetadata';

export interface DocumentModel {
  'content-type'?: string;
  created?: string;
  'last-modified'?: string;
  bucket?: string;
  name?: string;
  key?: string;
  path?: string;
  etag?: string;
  metadata?: DocumentMetadataModel;
  owner?: string;
  size?: number;
  version?: string;
  isFolder?: boolean;
}
