/**
 * Ladon Datacenter Edition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface FolderEntryModel { 
    value: string;
    id: string;
    size: number;
    date: number;
    type: string;
    data: Array<FolderEntryModel>;
}

